import type { Snippet } from './types'

export const jsSnippets: Snippet[] = [
  { label: 'clg', insert: 'console.log(${1:data})', detail: 'console.log' },
  { label: 'cw', insert: 'console.warn(${1:data})', detail: 'console.warn' },
  { label: 'ce', insert: 'console.error(${1:data})', detail: 'console.error' },
  { label: 'ci', insert: 'console.info(${1:data})', detail: 'console.info' },
  { label: 'ct', insert: 'console.time(${1:label})\n${2:// code}\nconsole.timeEnd(${1:label})', detail: 'console.time' },
  { label: 'cd', insert: 'console.dir(${1:obj}, { depth: null })', detail: 'console.dir' },
  { label: 'ctb', insert: 'console.table(${1:data})', detail: 'console.table' },
  { label: 'cgr', insert: 'console.group(${1:label})', detail: 'console.group' },
  { label: 'cge', insert: 'console.groupEnd()', detail: 'console.groupEnd' },
  { label: 'ccn', insert: 'console.count(${1:label})', detail: 'console.count' },
  { label: 'ccr', insert: 'console.countReset(${1:label})', detail: 'console.countReset' },
  { label: 'ctr', insert: 'console.trace(${1:label})', detail: 'console.trace' },
  { label: 'cls', insert: 'console.clear()', detail: 'console.clear' },
  { label: 'cdb', insert: 'debugger', detail: 'debugger' },

  { label: 'fn', insert: 'function ${1:name}(${2:params}) {\n\t${3:// body}\n}', detail: 'function' },
  { label: 'af', insert: 'async function ${1:name}(${2:params}) {\n\t${3:// body}\n}', detail: 'async function' },
  { label: 'afn', insert: 'async (${1:params}) => {\n\t${2:// body}\n}', detail: 'async arrow' },
  { label: 'afnc', insert: 'async (${1:params}) => ${2:value}', detail: 'async arrow concise' },
  { label: 'fni', insert: 'function* ${1:name}(${2:params}) {\n\t${3:// yield}\n}', detail: 'generator function' },
  { label: 'arr', insert: '(${1:params}) => {\n\t${2:// body}\n}', detail: 'arrow function' },
  { label: 'arrc', insert: '(${1:params}) => ${2:value}', detail: 'arrow concise' },
  { label: 'iife', insert: '(() => {\n\t${1:// body}\n})()', detail: 'IIFE' },
  { label: 'iifea', insert: '(async () => {\n\t${1:// body}\n})()', detail: 'async IIFE' },
  { label: 'mtd', insert: '${1:name}(${2:params}) {\n\t${3:// body}\n}', detail: 'method shorthand' },
  { label: 'gmtd', insert: 'get ${1:name}() {\n\treturn this._${1:name}\n}', detail: 'getter method' },
  { label: 'smt', insert: 'set ${1:name}(val) {\n\tthis._${1:name} = val\n}', detail: 'setter method' },
  { label: 'prop', insert: '${1:name}: ${2:value}', detail: 'object property' },
  { label: 'mprop', insert: '[${1:key}]: ${2:value}', detail: 'computed property' },

  { label: 'if', insert: 'if (${1:condition}) {\n\t${2:// body}\n}', detail: 'if' },
  { label: 'ife', insert: 'if (${1:condition}) {\n\t${2:// true}\n} else {\n\t${3:// false}\n}', detail: 'if/else' },
  { label: 'ifee', insert: 'if (${1:condition}) {\n\t${2:// body}\n} else if (${3:cond}) {\n\t${4:// body}\n} else {\n\t${5:// default}\n}', detail: 'if/else if/else' },
  { label: 'sw', insert: "switch (${1:value}) {\n\tcase '${2:case}':\n\t\t${3:// body}\n\t\tbreak\n\tdefault:\n\t\t${4:// default}\n}", detail: 'switch' },
  { label: 'tern', insert: '${1:condition} ? ${2:true} : ${3:false}', detail: 'ternary' },
  { label: 'and', insert: '${1:a} && ${2:b}', detail: 'logical AND' },
  { label: 'or', insert: '${1:a} || ${2:b}', detail: 'logical OR' },
  { label: 'nn', insert: '${1:a} ?? ${2:b}', detail: 'nullish coalescing' },

  { label: 'for', insert: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t${3:// body}\n}', detail: 'for loop' },
  { label: 'forr', insert: 'for (let ${1:i} = ${2:n} - 1; ${1:i} >= 0; ${1:i}--) {\n\t${3:// body}\n}', detail: 'for reverse' },
  { label: 'forof', insert: 'for (const ${1:item} of ${2:iterable}) {\n\t${3:// body}\n}', detail: 'for...of' },
  { label: 'forin', insert: 'for (const ${1:key} in ${2:obj}) {\n\t${3:// body}\n}', detail: 'for...in' },
  { label: 'forofe', insert: 'for (const [${1:key}, ${2:value}] of ${3:entries}) {\n\t${4:// body}\n}', detail: 'for...of entries' },
  { label: 'wh', insert: 'while (${1:condition}) {\n\t${2:// body}\n}', detail: 'while' },
  { label: 'dwh', insert: 'do {\n\t${1:// body}\n} while (${2:condition})', detail: 'do...while' },
  { label: 'lop', insert: 'for (let ${1:i} = 0, len = ${2:arr}.length; ${1:i} < len; ${1:i}++) {\n\t${3:// body}\n}', detail: 'for cached length' },

  { label: 'try', insert: 'try {\n\t${1:// code}\n} catch (${2:err}) {\n\t${3:// handle}\n}', detail: 'try/catch' },
  { label: 'tryf', insert: 'try {\n\t${1:// code}\n} catch (${2:err}) {\n\t${3:// handle}\n} finally {\n\t${4:// cleanup}\n}', detail: 'try/catch/finally' },
  { label: 'tryret', insert: 'try {\n\treturn ${1:result}\n} catch (${2:err}) {\n\treturn ${3:fallback}\n}', detail: 'try with return' },
  { label: 'trya', insert: 'try {\n\t${1:// code}\n} catch (err) {\n\tconsole.error(err)\n}', detail: 'try catch console' },

  { label: 'imp', insert: "import ${1:module} from '${2:path}'", detail: 'import default' },
  { label: 'impn', insert: "import { ${1:name} } from '${2:path}'", detail: 'import named' },
  { label: 'impa', insert: "import * as ${1:alias} from '${2:path}'", detail: 'import all' },
  { label: 'impas', insert: "import ${1:name} as ${2:alias} from '${3:path}'", detail: 'import alias' },
  { label: 'impi', insert: "import '${1:path}'", detail: 'import side effect' },
  { label: 'expd', insert: 'export default ${1:value}', detail: 'export default' },
  { label: 'expn', insert: 'export { ${1:name} }', detail: 'export named' },
  { label: 'expf', insert: 'export function ${1:name}(${2:params}) {\n\t${3:// body}\n}', detail: 'export function' },
  { label: 'expc', insert: 'export class ${1:Name} {\n\t${2:// body}\n}', detail: 'export class' },
  { label: 'expv', insert: 'export const ${1:name} = ${2:value}', detail: 'export const' },
  { label: 'exple', insert: "export { ${1:name} } from '${2:path}'", detail: 're-export' },
  { label: 'expa', insert: "export * as ${1:alias} from '${2:path}'", detail: 're-export all as' },

  { label: 'promise', insert: 'new Promise((${1:resolve}, ${2:reject}) => {\n\t${3:// code}\n})', detail: 'new Promise' },
  { label: 'promisef', insert: 'new Promise(${1:(resolve) => resolve(${2:value})})', detail: 'Promise resolved' },
  { label: 'promiser', insert: 'new Promise(${1:(_, reject) => reject(new Error("${2:msg}"))})', detail: 'Promise rejected' },
  { label: 'then', insert: '.then(${1:result => {\n\t${2:// handle}\n}})', detail: '.then()' },
  { label: 'catch', insert: '.catch(${1:err => {\n\t${2:// handle}\n}})', detail: '.catch()' },
  { label: 'finally', insert: '.finally(() => {\n\t${1:// cleanup}\n})', detail: '.finally()' },
  { label: 'pall', insert: 'Promise.all([${1:p1}, ${2:p2}])', detail: 'Promise.all' },
  { label: 'pallset', insert: 'Promise.allSettled([${1:p1}, ${2:p2}])', detail: 'Promise.allSettled' },
  { label: 'prace', insert: 'Promise.race([${1:p1}, ${2:p2}])', detail: 'Promise.race' },
  { label: 'pany', insert: 'Promise.any([${1:p1}, ${2:p2}])', detail: 'Promise.any' },
  { label: 'presolve', insert: 'Promise.resolve(${1:value})', detail: 'Promise.resolve' },
  { label: 'preject', insert: 'Promise.reject(${1:reason})', detail: 'Promise.reject' },
  { label: 'aw', insert: 'const ${1:result} = await ${2:promise}', detail: 'await' },
  { label: 'awt', insert: 'await ${1:promise}', detail: 'await (no const)' },

  { label: 'map', insert: '.map((${1:item}) => ${2:item})', detail: '.map()' },
  { label: 'mp', insert: '.map(${1:item} => ${2:item})', detail: '.map() short' },
  { label: 'filter', insert: '.filter((${1:item}) => ${2:condition})', detail: '.filter()' },
  { label: 'ft', insert: '.filter(${1:item} => ${2:condition})', detail: '.filter() short' },
  { label: 'reduce', insert: '.reduce((${1:acc}, ${2:item}) => {\n\t${3:return acc}\n}, ${4:init})', detail: '.reduce()' },
  { label: 'find', insert: '.find((${1:item}) => ${2:condition})', detail: '.find()' },
  { label: 'fd', insert: '.find(${1:item} => ${2:condition})', detail: '.find() short' },
  { label: 'findi', insert: '.findIndex((${1:item}) => ${2:condition})', detail: '.findIndex()' },
  { label: 'findl', insert: '.findLast((${1:item}) => ${2:condition})', detail: '.findLast()' },
  { label: 'findli', insert: '.findLastIndex((${1:item}) => ${2:condition})', detail: '.findLastIndex()' },
  { label: 'some', insert: '.some((${1:item}) => ${2:condition})', detail: '.some()' },
  { label: 'every', insert: '.every((${1:item}) => ${2:condition})', detail: '.every()' },
  { label: 'forEach', insert: '.forEach((${1:item}) => {\n\t${2:// body}\n})', detail: '.forEach()' },
  { label: 'fe', insert: '.forEach(${1:item} => {\n\t${2:// body}\n})', detail: '.forEach() short' },
  { label: 'flat', insert: '.flat(${1:1})', detail: '.flat()' },
  { label: 'flatMap', insert: '.flatMap((${1:item}) => ${2:mapped})', detail: '.flatMap()' },
  { label: 'sort', insert: '.sort((${1:a}, ${2:b}) => ${1:a} - ${2:b})', detail: '.sort() numeric' },
  { label: 'sorts', insert: '.sort((${1:a}, ${2:b}) => ${1:a}.localeCompare(${2:b}))', detail: '.sort() string' },
  { label: 'sortd', insert: '.sort((${1:a}, ${2:b}) => ${2:b} - ${1:a})', detail: '.sort() desc' },
  { label: 'reverse', insert: '.reverse()', detail: '.reverse()' },
  { label: 'splice', insert: '.splice(${1:start}, ${2:count})', detail: '.splice()' },
  { label: 'spla', insert: '.splice(${1:start}, ${2:count}, ${3:replacement})', detail: '.splice() with replace' },
  { label: 'slice', insert: '.slice(${1:start}, ${2:end})', detail: '.slice()' },
  { label: 'slicen', insert: '.slice(-${1:n})', detail: '.slice() last n' },

  { label: 'includes', insert: '.includes(${1:value})', detail: '.includes()' },
  { label: 'indexof', insert: '.indexOf(${1:value})', detail: '.indexOf()' },
  { label: 'lastindexof', insert: '.lastIndexOf(${1:value})', detail: '.lastIndexOf()' },
  { label: 'findindex', insert: '.findIndex(${1:item => item === value})', detail: '.findIndex()' },
  { label: 'concat', insert: '.concat(${1:other})', detail: '.concat()' },
  { label: 'join', insert: '.join(${1:", "})', detail: '.join()' },
  { label: 'split', insert: '.split(${1:delimiter})', detail: '.split()' },
  { label: 'replace', insert: '.replace(${1:search}, ${2:replace})', detail: '.replace()' },
  { label: 'replaceAll', insert: '.replaceAll(${1:search}, ${2:replace})', detail: '.replaceAll()' },
  { label: 'trim', insert: '.trim()', detail: '.trim()' },
  { label: 'trimL', insert: '.trimStart()', detail: '.trimStart()' },
  { label: 'trimR', insert: '.trimEnd()', detail: '.trimEnd()' },
  { label: 'padS', insert: '.padStart(${1:length}, ${2:"0"})', detail: '.padStart()' },
  { label: 'padE', insert: '.padEnd(${1:length}, ${2:" "})', detail: '.padEnd()' },
  { label: 'repeat', insert: '.repeat(${1:count})', detail: '.repeat()' },
  { label: 'match', insert: '.match(${1:/regex/})', detail: '.match()' },
  { label: 'matchAll', insert: '.matchAll(${1:/regex/})', detail: '.matchAll()' },
  { label: 'search', insert: '.search(${1:/regex/})', detail: '.search()' },
  { label: 'startsWith', insert: '.startsWith(${1:value})', detail: '.startsWith()' },
  { label: 'endsWith', insert: '.endsWith(${1:value})', detail: '.endsWith()' },
  { label: 'charA', insert: '.charAt(${1:index})', detail: '.charAt()' },
  { label: 'charC', insert: '.charCodeAt(${1:index})', detail: '.charCodeAt()' },
  { label: 'at', insert: '.at(${1:index})', detail: '.at()' },
  { label: 'locale', insert: '.localeCompare(${1:other})', detail: '.localeCompare()' },
  { label: 'toL', insert: '.toLowerCase()', detail: '.toLowerCase()' },
  { label: 'toU', insert: '.toUpperCase()', detail: '.toUpperCase()' },
  { label: 'substr', insert: '.substring(${1:start}, ${2:end})', detail: '.substring()' },
  { label: 'num', insert: 'Number(${1:value})', detail: 'Number()' },
  { label: 'int', insert: 'parseInt(${1:value}, ${2:10})', detail: 'parseInt()' },
  { label: 'flt', insert: 'parseFloat(${1:value})', detail: 'parseFloat()' },

  { label: 'keys', insert: 'Object.keys(${1:obj})', detail: 'Object.keys' },
  { label: 'values', insert: 'Object.values(${1:obj})', detail: 'Object.values' },
  { label: 'entries', insert: 'Object.entries(${1:obj})', detail: 'Object.entries' },
  { label: 'fromEntries', insert: 'Object.fromEntries(${1:entries})', detail: 'Object.fromEntries' },
  { label: 'assign', insert: 'Object.assign(${1:target}, ${2:source})', detail: 'Object.assign' },
  { label: 'create', insert: 'Object.create(${1:prototype})', detail: 'Object.create' },
  { label: 'freeze', insert: 'Object.freeze(${1:obj})', detail: 'Object.freeze' },
  { label: 'seal', insert: 'Object.seal(${1:obj})', detail: 'Object.seal' },
  { label: 'defineProp', insert: "Object.defineProperty(${1:obj}, '${2:prop}', {\n\tvalue: ${3:value},\n\twritable: ${4:true},\n\tenumerable: ${5:true},\n\tconfigurable: ${6:true}\n})", detail: 'Object.defineProperty' },
  { label: 'defineProps', insert: "Object.defineProperties(${1:obj}, {\n\t'${2:prop}': {\n\t\tvalue: ${3:value},\n\t\twritable: ${4:true}\n\t}\n})", detail: 'Object.defineProperties' },
  { label: 'getPropDesc', insert: "Object.getOwnPropertyDescriptor(${1:obj}, '${2:prop}')", detail: 'Object.getOwnPropertyDescriptor' },
  { label: 'hasOwn', insert: "Object.hasOwn(${1:obj}, '${2:prop}')", detail: 'Object.hasOwn' },
  { label: 'is', insert: 'Object.is(${1:a}, ${2:b})', detail: 'Object.is' },
  { label: 'from', insert: 'Object.from(${1:obj})', detail: 'Object.from' },

  { label: 'mapGet', insert: "new Map([['${1:key}', ${2:value}]])", detail: 'new Map' },
  { label: 'mapSet', insert: '${1:map}.set(${2:key}, ${3:value})', detail: 'Map.set' },
  { label: 'mapGet', insert: '${1:map}.get(${2:key})', detail: 'Map.get' },
  { label: 'mapHas', insert: '${1:map}.has(${2:key})', detail: 'Map.has' },
  { label: 'mapDel', insert: '${1:map}.delete(${2:key})', detail: 'Map.delete' },
  { label: 'mapForEach', insert: '${1:map}.forEach((${2:value}, ${3:key}) => {\n\t${4:// body}\n})', detail: 'Map.forEach' },

  { label: 'setAdd', insert: '${1:set}.add(${2:value})', detail: 'Set.add' },
  { label: 'setHas', insert: '${1:set}.has(${2:value})', detail: 'Set.has' },
  { label: 'setDel', insert: '${1:set}.delete(${2:value})', detail: 'Set.delete' },
  { label: 'setFrom', insert: 'new Set(${1:array})', detail: 'new Set from array' },

  { label: 'arrFrom', insert: 'Array.from(${1:arrayLike})', detail: 'Array.from' },
  { label: 'arrIs', insert: 'Array.isArray(${1:value})', detail: 'Array.isArray' },
  { label: 'arrOf', insert: 'Array.of(${1:items})', detail: 'Array.of' },
  { label: 'arrFill', insert: 'new Array(${1:length}).fill(${2:value})', detail: 'Array fill' },

  { label: 'str', insert: "'${1:text}'", detail: 'single quote string' },
  { label: 'strd', insert: '"${1:text}"', detail: 'double quote string' },
  { label: 'strt', insert: '`${1:text}`', detail: 'template literal' },
  { label: 'strinter', insert: `\`\${${1:expr}}\``, detail: 'template interpolation' },
  { label: 'strmulti', insert: '`\n\t${1:text}\n`', detail: 'multiline template' },

  { label: 'const', insert: 'const ${1:name} = ${2:value}', detail: 'const' },
  { label: 'let', insert: 'let ${1:name} = ${2:value}', detail: 'let' },
  { label: 'var', insert: 'var ${1:name} = ${2:value}', detail: 'var' },
  { label: 'destr', insert: 'const { ${1:key} } = ${2:obj}', detail: 'destructuring object' },
  { label: 'destra', insert: 'const [${1:first}, ${2:rest}] = ${3:arr}', detail: 'destructuring array' },
  { label: 'destrd', insert: 'const { ${1:key}: ${2:alias} } = ${3:obj}', detail: 'destructuring rename' },
  { label: 'destrd', insert: 'const { ${1:key} = ${2:default} } = ${3:obj}', detail: 'destructuring default' },
  { label: 'spread', insert: '...${1:obj}', detail: 'spread' },
  { label: 'restp', insert: '...${1:args}', detail: 'rest params' },
  { label: 'objsp', insert: '{ ...${1:obj}, ${2:key}: ${3:value} }', detail: 'spread + override' },

  { label: 'class', insert: 'class ${1:Name} {\n\tconstructor(${2:params}) {\n\t\t${3:// init}\n\t}\n}', detail: 'class' },
  { label: 'classe', insert: 'class ${1:Name} extends ${2:Base} {\n\tconstructor(${3:params}) {\n\t\tsuper(${4:params})\n\t\t${5:// init}\n\t}\n}', detail: 'class extends' },
  { label: 'classm', insert: 'class ${1:Name} {\n\tstatic ${2:method}(${3:params}) {\n\t\t${4:// body}\n\t}\n}', detail: 'static method' },
  { label: 'priv', insert: '#${1:name} = ${2:value}', detail: 'private field' },
  { label: 'get', insert: 'get ${1:name}() {\n\treturn this.#${1:name}\n}', detail: 'private getter' },
  { label: 'set', insert: 'set ${1:name}(val) {\n\tthis.#${1:name} = val\n}', detail: 'private setter' },

  { label: 'sym', insert: 'Symbol(${1:description})', detail: 'Symbol' },
  { label: 'iter', insert: '[Symbol.iterator]() {\n\tlet ${1:i} = 0\n\tconst ${2:items} = this.${3:data}\n\treturn {\n\t\tnext() {\n\t\t\treturn ${1:i} < ${2:items}.length\n\t\t\t\t? { value: ${2:items}[${1:i}++], done: false }\n\t\t\t\t: { done: true }\n\t\t}\n\t}\n}', detail: 'Symbol.iterator' },

  { label: 'async', insert: 'async (${1:params}) => {\n\t${2:// body}\n}', detail: 'async arrow' },
  { label: 'thenn', insert: '.then(${1:result})', detail: '.then() short' },
  { label: 'catchh', insert: '.catch(${1:err})', detail: '.catch() short' },
  { label: 'awf', insert: 'const ${1:result} = await fetch(${2:url})', detail: 'await fetch' },
  { label: 'awr', insert: 'const ${1:data} = await ${2:res}.json()', detail: 'await res.json()' },

  { label: 'fetch', insert: "fetch('${1:url}')", detail: 'fetch' },
  { label: 'fetchj', insert: "fetch('${1:url}').then(${2:r} => ${2:r}.json())", detail: 'fetch JSON' },
  { label: 'fetcha', insert: "fetch('${1:url}', {\n\tmethod: '${2:POST}',\n\theaders: {\n\t\t'Content-Type': 'application/json'\n\t},\n\tbody: JSON.stringify(${3:data})\n})", detail: 'fetch POST' },

  { label: 'xhr', insert: "const ${1:xhr} = new XMLHttpRequest()\n${1:xhr}.open('${2:GET}', '${3:url}')\n${1:xhr}.send()", detail: 'XMLHttpRequest' },

  { label: 'timer', insert: 'setTimeout(() => {\n\t${1:// body}\n}, ${2:1000})', detail: 'setTimeout' },
  { label: 'interv', insert: 'setInterval(() => {\n\t${1:// body}\n}, ${2:1000})', detail: 'setInterval' },
  { label: 'timerC', insert: 'const ${1:id} = setTimeout(${2:fn}, ${3:1000})\nclearTimeout(${1:id})', detail: 'setTimeout + clearTimeout' },
  { label: 'intervC', insert: 'const ${1:id} = setInterval(${2:fn}, ${3:1000})\nclearInterval(${1:id})', detail: 'setInterval + clearInterval' },
  { label: 'rAF', insert: 'requestAnimationFrame(${1:callback})', detail: 'requestAnimationFrame' },
  { label: 'cAF', insert: 'cancelAnimationFrame(${1:id})', detail: 'cancelAnimationFrame' },
  { label: 'immediate', insert: 'setImmediate(() => {\n\t${1:// body}\n})', detail: 'setImmediate' },

  { label: 'date', insert: 'new Date()', detail: 'new Date' },
  { label: 'dateNow', insert: 'Date.now()', detail: 'Date.now' },
  { label: 'dateFrom', insert: "new Date('${1:2024-01-01}')", detail: 'Date from string' },
  { label: 'dateTs', insert: 'new Date(${1:timestamp})', detail: 'Date from timestamp' },
  { label: 'dateGet', insert: '${1:date}.getFullYear()', detail: 'getFullYear' },
  { label: 'dateMonth', insert: '${1:date}.getMonth()', detail: 'getMonth' },
  { label: 'dateDay', insert: '${1:date}.getDate()', detail: 'getDate' },
  { label: 'dateHour', insert: '${1:date}.getHours()', detail: 'getHours' },
  { label: 'dateMin', insert: '${1:date}.getMinutes()', detail: 'getMinutes' },
  { label: 'dateSec', insert: '${1:date}.getSeconds()', detail: 'getSeconds' },
  { label: 'dateMs', insert: '${1:date}.getMilliseconds()', detail: 'getMilliseconds' },
  { label: 'dateISO', insert: '${1:date}.toISOString()', detail: 'toISOString' },
  { label: 'dateLocale', insert: '${1:date}.toLocaleDateString()', detail: 'toLocaleDateString' },
  { label: 'dateParse', insert: "Date.parse('${1:2024-01-01}')", detail: 'Date.parse' },

  { label: 'mathPi', insert: 'Math.PI', detail: 'Math.PI' },
  { label: 'mathE', insert: 'Math.E', detail: 'Math.E' },
  { label: 'mathAbs', insert: 'Math.abs(${1:value})', detail: 'Math.abs' },
  { label: 'mathCeil', insert: 'Math.ceil(${1:value})', detail: 'Math.ceil' },
  { label: 'mathFloor', insert: 'Math.floor(${1:value})', detail: 'Math.floor' },
  { label: 'mathRound', insert: 'Math.round(${1:value})', detail: 'Math.round' },
  { label: 'mathTrunc', insert: 'Math.trunc(${1:value})', detail: 'Math.trunc' },
  { label: 'mathMax', insert: 'Math.max(${1:a}, ${2:b})', detail: 'Math.max' },
  { label: 'mathMin', insert: 'Math.min(${1:a}, ${2:b})', detail: 'Math.min' },
  { label: 'mathRandom', insert: 'Math.random()', detail: 'Math.random' },
  { label: 'mathRand', insert: 'Math.floor(Math.random() * ${1:max})', detail: 'random int' },
  { label: 'mathRandR', insert: 'Math.random() * (${1:max} - ${2:min}) + ${2:min}', detail: 'random range' },
  { label: 'mathPow', insert: 'Math.pow(${1:base}, ${2:exp})', detail: 'Math.pow' },
  { label: 'mathSqrt', insert: 'Math.sqrt(${1:value})', detail: 'Math.sqrt' },
  { label: 'mathLog', insert: 'Math.log(${1:value})', detail: 'Math.log' },
  { label: 'mathLog2', insert: 'Math.log2(${1:value})', detail: 'Math.log2' },
  { label: 'mathLog10', insert: 'Math.log10(${1:value})', detail: 'Math.log10' },
  { label: 'mathExp', insert: 'Math.exp(${1:value})', detail: 'Math.exp' },
  { label: 'mathSin', insert: 'Math.sin(${1:value})', detail: 'Math.sin' },
  { label: 'mathCos', insert: 'Math.cos(${1:value})', detail: 'Math.cos' },
  { label: 'mathTan', insert: 'Math.tan(${1:value})', detail: 'Math.tan' },
  { label: 'mathAsin', insert: 'Math.asin(${1:value})', detail: 'Math.asin' },
  { label: 'mathAcos', insert: 'Math.acos(${1:value})', detail: 'Math.acos' },
  { label: 'mathAtan', insert: 'Math.atan(${1:value})', detail: 'Math.atan' },
  { label: 'mathAtan2', insert: 'Math.atan2(${1:y}, ${2:x})', detail: 'Math.atan2' },
  { label: 'mathSinh', insert: 'Math.sinh(${1:value})', detail: 'Math.sinh' },
  { label: 'mathCosh', insert: 'Math.cosh(${1:value})', detail: 'Math.cosh' },
  { label: 'mathTanh', insert: 'Math.tanh(${1:value})', detail: 'Math.tanh' },
  { label: 'mathSign', insert: 'Math.sign(${1:value})', detail: 'Math.sign' },
  { label: 'mathClamp', insert: 'Math.min(Math.max(${1:value}, ${2:min}), ${3:max})', detail: 'clamp value' },
  { label: 'mathAvg', insert: '(${1:arr}).reduce((${2:a}, ${3:b}) => ${2:a} + ${3:b}, 0) / ${1:arr}.length', detail: 'array average' },

  { label: 'jsonParse', insert: 'JSON.parse(${1:str})', detail: 'JSON.parse' },
  { label: 'jsonStr', insert: 'JSON.stringify(${1:obj})', detail: 'JSON.stringify' },
  { label: 'jsonStrf', insert: 'JSON.stringify(${1:obj}, null, ${2:2})', detail: 'JSON.stringify formatted' },
  { label: 'jsonCopy', insert: 'JSON.parse(JSON.stringify(${1:obj}))', detail: 'deep copy' },

  { label: 'encode', insert: 'encodeURIComponent(${1:str})', detail: 'encodeURIComponent' },
  { label: 'decode', insert: 'decodeURIComponent(${1:str})', detail: 'decodeURIComponent' },
  { label: 'encodeURI', insert: 'encodeURI(${1:str})', detail: 'encodeURI' },
  { label: 'decodeURI', insert: 'decodeURI(${1:str})', detail: 'decodeURI' },
  { label: 'atob', insert: 'atob(${1:str})', detail: 'atob (decode base64)' },
  { label: 'btoa', insert: 'btoa(${1:str})', detail: 'btoa (encode base64)' },

  { label: 'regExp', insert: 'new RegExp(${1:pattern}, ${2:"g"})', detail: 'new RegExp' },
  { label: 'regL', insert: '/${1:pattern}/g', detail: 'regex literal' },
  { label: 'regTest', insert: '${1:regex}.test(${2:str})', detail: 'RegExp.test' },
  { label: 'regExec', insert: '${1:regex}.exec(${2:str})', detail: 'RegExp.exec' },

  { label: 'weakmap', insert: 'new WeakMap()', detail: 'WeakMap' },
  { label: 'weakset', insert: 'new WeakSet()', detail: 'WeakSet' },
  { label: 'weakref', insert: 'new WeakRef(${1:obj})', detail: 'WeakRef' },
  { label: 'proxy', insert: 'new Proxy(${1:target}, {\n\tget(${2:target}, ${3:prop}) {\n\t\t${4:// intercept get}\n\t},\n\tset(${2:target}, ${3:prop}, ${4:value}) {\n\t\t${5:// intercept set}\n\t}\n})', detail: 'Proxy' },
  { label: 'reflect', insert: 'Reflect.${1:method}(${2:target})', detail: 'Reflect' },

  { label: 'abort', insert: 'new AbortController()', detail: 'AbortController' },
  { label: 'timeout', insert: 'AbortSignal.timeout(${1:ms})', detail: 'AbortSignal.timeout' },

  { label: 'textEncoder', insert: 'new TextEncoder()', detail: 'TextEncoder' },
  { label: 'textDecoder', insert: 'new TextDecoder()', detail: 'TextDecoder' },

  { label: 'url', insert: "new URL('${1:url}')", detail: 'new URL' },
  { label: 'urlp', insert: 'new URLSearchParams(${1:params})', detail: 'new URLSearchParams' },
  { label: 'urla', insert: 'new URL(${1:path}, ${2:base})', detail: 'URL relative' },

  { label: 'crypto', insert: 'crypto.randomUUID()', detail: 'crypto.randomUUID' },
  { label: 'cryptoSha', insert: "crypto.subtle.digest('${1:SHA-256}', ${2:data})", detail: 'crypto.subtle.digest' },

  { label: 'queueMicro', insert: 'queueMicrotask(${1:fn})', detail: 'queueMicrotask' },
  { label: 'structuredClone', insert: 'structuredClone(${1:obj})', detail: 'structuredClone' },

  { label: 'forofentries', insert: 'for (const [${1:key}, ${2:val}] of Object.entries(${3:obj})) {\n\t${4:// body}\n}', detail: 'for Object.entries' },

  { label: 'timeoutc', insert: 'const ${1:id} = setTimeout(() => {\n\t${2:// body}\n}, ${3:1000})', detail: 'setTimeout const' },
  { label: 'intervalc', insert: 'const ${1:id} = setInterval(() => {\n\t${2:// body}\n}, ${3:1000})', detail: 'setInterval const' },

  { label: 'dom', insert: "document.querySelector('${1:selector}')", detail: 'querySelector' },
  { label: 'doma', insert: "document.querySelectorAll('${1:selector}')", detail: 'querySelectorAll' },
  { label: 'domid', insert: "document.getElementById('${1:id}')", detail: 'getElementById' },
  { label: 'domcls', insert: "document.getElementsByClassName('${1:class}')", detail: 'getElementsByClassName' },
  { label: 'domtag', insert: "document.getElementsByTagName('${1:tag}')", detail: 'getElementsByTagName' },
  { label: 'domcre', insert: "document.createElement('${1:tag}')", detail: 'createElement' },
  { label: 'domtext', insert: 'document.createTextNode(${1:text})', detail: 'createTextNode' },
  { label: 'domfrag', insert: 'document.createDocumentFragment()', detail: 'createDocumentFragment' },
  { label: 'adde', insert: '${1:el}.addEventListener(${2:"click"}, ${3:(e) => {\n\t${4:// handler}\n}})', detail: 'addEventListener' },
  { label: 'removee', insert: '${1:el}.removeEventListener(${2:"click"}, ${3:handler})', detail: 'removeEventListener' },
  { label: 'addd', insert: '${1:parent}.appendChild(${2:child})', detail: 'appendChild' },
  { label: 'addb', insert: '${1:parent}.prepend(${2:child})', detail: 'prepend' },
  { label: 'remove', insert: '${1:el}.remove()', detail: 'remove element' },
  { label: 'clone', insert: '${1:el}.cloneNode(${2:true})', detail: 'cloneNode' },
  { label: 'attr', insert: '${1:el}.setAttribute(${2:"name"}, ${3:"value"})', detail: 'setAttribute' },
  { label: 'geta', insert: '${1:el}.getAttribute(${2:"name"})', detail: 'getAttribute' },
  { label: 'hasa', insert: '${1:el}.hasAttribute(${2:"name"})', detail: 'hasAttribute' },
  { label: 'rema', insert: '${1:el}.removeAttribute(${2:"name"})', detail: 'removeAttribute' },
  { label: 'dataset', insert: '${1:el}.dataset.${2:key}', detail: 'dataset' },
  { label: 'classadd', insert: '${1:el}.classList.add(${2:"class"})', detail: 'classList.add' },
  { label: 'classrem', insert: '${1:el}.classList.remove(${2:"class"})', detail: 'classList.remove' },
  { label: 'classtog', insert: '${1:el}.classList.toggle(${2:"class"})', detail: 'classList.toggle' },
  { label: 'classhas', insert: '${1:el}.classList.contains(${2:"class"})', detail: 'classList.contains' },
  { label: 'styles', insert: '${1:el}.style.${2:prop} = ${3:value}', detail: 'style' },
  { label: 'getcom', insert: "getComputedStyle(${1:el}).${2:prop}", detail: 'getComputedStyle' },
  { label: 'parent', insert: '${1:el}.parentElement', detail: 'parentElement' },
  { label: 'children', insert: '${1:el}.children', detail: 'children' },
  { label: 'first', insert: '${1:el}.firstElementChild', detail: 'firstElementChild' },
  { label: 'last', insert: '${1:el}.lastElementChild', detail: 'lastElementChild' },
  { label: 'prev', insert: '${1:el}.previousElementSibling', detail: 'previousElementSibling' },
  { label: 'next', insert: '${1:el}.nextElementSibling', detail: 'nextElementSibling' },
  { label: 'html', insert: '${1:el}.innerHTML', detail: 'innerHTML' },
  { label: 'textc', insert: '${1:el}.textContent', detail: 'textContent' },
  { label: 'inner', insert: '${1:el}.innerText', detail: 'innerText' },
  { label: 'offsetw', insert: '${1:el}.offsetWidth', detail: 'offsetWidth' },
  { label: 'offseth', insert: '${1:el}.offsetHeight', detail: 'offsetHeight' },
  { label: 'scrollt', insert: '${1:el}.scrollTop', detail: 'scrollTop' },
  { label: 'scrolll', insert: '${1:el}.scrollLeft', detail: 'scrollLeft' },
  { label: 'bcr', insert: '${1:el}.getBoundingClientRect()', detail: 'getBoundingClientRect' },

  { label: 'mutation', insert: "new MutationObserver((${1:mutations}) => {\n\t${2:// observe}\n}).observe(${3:target}, { childList: ${4:true}, subtree: ${5:true} })", detail: 'MutationObserver' },
  { label: 'resize', insert: "new ResizeObserver((${1:entries}) => {\n\t${2:// observe}\n}).observe(${3:el})", detail: 'ResizeObserver' },
  { label: 'intersection', insert: "new IntersectionObserver((${1:entries}) => {\n\t${2:// observe}\n}).observe(${3:el})", detail: 'IntersectionObserver' },
  { label: 'perf', insert: 'performance.now()', detail: 'performance.now' },
  { label: 'perfmark', insert: 'performance.mark(${1:"start"})', detail: 'performance.mark' },
  { label: 'perfmeas', insert: 'performance.measure(${1:"duration"}, ${2:"start"})', detail: 'performance.measure' },

  { label: 'storage', insert: "localStorage.setItem('${1:key}', ${2:value})", detail: 'localStorage.setItem' },
  { label: 'storageg', insert: "localStorage.getItem('${1:key}')", detail: 'localStorage.getItem' },
  { label: 'storager', insert: "localStorage.removeItem('${1:key}')", detail: 'localStorage.removeItem' },
  { label: 'storagec', insert: 'localStorage.clear()', detail: 'localStorage.clear' },
  { label: 'session', insert: "sessionStorage.setItem('${1:key}', ${2:value})", detail: 'sessionStorage.setItem' },
  { label: 'sessiong', insert: "sessionStorage.getItem('${1:key}')", detail: 'sessionStorage.getItem' },

  { label: 'cookie', insert: "document.cookie = '${1:name}=${2:value}; path=/${3:; max-age=86400}'", detail: 'set cookie' },
  { label: 'cookieg', insert: "document.cookie", detail: 'get cookies' },

  { label: 'history', insert: "history.pushState(${1:state}, '', '${2:url}')", detail: 'history.pushState' },
  { label: 'historyb', insert: 'history.back()', detail: 'history.back' },
  { label: 'historyf', insert: 'history.forward()', detail: 'history.forward' },

  { label: 'postm', insert: "window.postMessage(${1:data}, '${2:*}')", detail: 'postMessage' },
  { label: 'postl', insert: "window.addEventListener('message', (${1:e}) => {\n\t${2:// handle}\n})", detail: 'on message' },

  { label: 'blob', insert: 'new Blob([${1:data}], { type: "${2:text/plain}" })', detail: 'new Blob' },
  { label: 'file', insert: 'new File([${1:data}], ${2:"filename"}, { type: "${3:text/plain}" })', detail: 'new File' },
  { label: 'fd', insert: 'new FormData()', detail: 'new FormData' },
  { label: 'fds', insert: '${1:fd}.append(${2:key}, ${3:value})', detail: 'FormData.append' },
  { label: 'download', insert: "const ${1:a} = document.createElement('a')\n${1:a}.href = URL.createObjectURL(${2:blob})\n${1:a}.download = '${3:filename}'\n${1:a}.click()", detail: 'download file' },

  { label: 'ws', insert: "new WebSocket('${1:url}')", detail: 'new WebSocket' },
  { label: 'wss', insert: "${1:ws}.send(${2:data})", detail: 'ws.send' },
  { label: 'wson', insert: "${1:ws}.onmessage = (${2:e}) => {\n\t${3:// handle}\n}", detail: 'ws.onmessage' },

  { label: 'requestAnimationFrame', insert: 'requestAnimationFrame((${1:time}) => {\n\t${2:// animate}\n})', detail: 'requestAnimationFrame' },
  { label: 'canvas', insert: "${1:el}.getContext('${2:2d}')", detail: 'canvas context' },

  { label: 'worker', insert: "new Worker('${1:script}')", detail: 'new Worker' },
  { label: 'workerp', insert: "new SharedWorker('${1:script}')", detail: 'new SharedWorker' },

  { label: 'service', insert: "navigator.serviceWorker.register('${1:script}')", detail: 'serviceWorker.register' },

  { label: 'geol', insert: "navigator.geolocation.getCurrentPosition(${1:(pos) => {\n\t${2:// handle}\n}})", detail: 'geolocation' },

  { label: 'notification', insert: "Notification.requestPermission().then(${1:perm} => {\n\t${2:// handle}\n})", detail: 'Notification.requestPermission' },
  { label: 'notify', insert: "new Notification('${1:title}', { body: '${2:message}' })", detail: 'new Notification' },

  { label: 'asynciter', insert: 'async *${1:name}(${2:params}) {\n\t${3:// yield}\n}', detail: 'async generator' },
  { label: 'forawait', insert: 'for await (const ${1:item} of ${2:iterable}) {\n\t${3:// body}\n}', detail: 'for await...of' },

  { label: 'mapnew', insert: 'new Map()', detail: 'new Map' },
  { label: 'mapfrom', insert: 'new Map(Object.entries(${1:obj}))', detail: 'Map from object' },
  { label: 'mapset', insert: '${1:map}.set(${2:key}, ${3:value})', detail: 'Map.set' },
  { label: 'mapget', insert: '${1:map}.get(${2:key})', detail: 'Map.get' },
  { label: 'mapgetd', insert: '${1:map}.get(${2:key}) ?? ${3:default}', detail: 'Map.get with default' },
  { label: 'mapdel', insert: '${1:map}.delete(${2:key})', detail: 'Map.delete' },
  { label: 'maphas', insert: '${1:map}.has(${2:key})', detail: 'Map.has' },
  { label: 'mapkeys', insert: '${1:map}.keys()', detail: 'Map.keys' },
  { label: 'mapvals', insert: '${1:map}.values()', detail: 'Map.values' },
  { label: 'mapents', insert: '${1:map}.entries()', detail: 'Map.entries' },
  { label: 'mapclear', insert: '${1:map}.clear()', detail: 'Map.clear' },
  { label: 'mapsize', insert: '${1:map}.size', detail: 'Map.size' },
  { label: 'mapobj', insert: 'Object.fromEntries(${1:map})', detail: 'Map to Object' },

  { label: 'setnew', insert: 'new Set()', detail: 'new Set' },
  { label: 'setfrom', insert: 'new Set(${1:arr})', detail: 'Set from array' },
  { label: 'setadd', insert: '${1:set}.add(${2:value})', detail: 'Set.add' },
  { label: 'sethas', insert: '${1:set}.has(${2:value})', detail: 'Set.has' },
  { label: 'setdel', insert: '${1:set}.delete(${2:value})', detail: 'Set.delete' },
  { label: 'setclear', insert: '${1:set}.clear()', detail: 'Set.clear' },
  { label: 'setsize', insert: '${1:set}.size', detail: 'Set.size' },
  { label: 'setarr', insert: 'Array.from(${1:set})', detail: 'Set to Array' },
  { label: 'setunion', insert: 'new Set([...${1:a}, ...${2:b}])', detail: 'Set union' },
  { label: 'setinter', insert: 'new Set([...${1:a}].filter(${2:x} => ${3:b}.has(${2:x})))', detail: 'Set intersection' },
  { label: 'setdiff', insert: 'new Set([...${1:a}].filter(${2:x} => !${3:b}.has(${2:x})))', detail: 'Set difference' },

  { label: 'typedArr', insert: 'new Uint8Array(${1:length})', detail: 'Uint8Array' },
  { label: 'int16', insert: 'new Int16Array(${1:length})', detail: 'Int16Array' },
  { label: 'float32', insert: 'new Float32Array(${1:length})', detail: 'Float32Array' },
  { label: 'buffer', insert: 'new ArrayBuffer(${1:length})', detail: 'ArrayBuffer' },

  { label: 'error', insert: 'throw new Error(${1:"message"})', detail: 'throw Error' },
  { label: 'errorr', insert: 'throw new RangeError(${1:"message"})', detail: 'RangeError' },
  { label: 'errort', insert: 'throw new TypeError(${1:"message"})', detail: 'TypeError' },
  { label: 'errorr', insert: 'throw new ReferenceError(${1:"message"})', detail: 'ReferenceError' },
  { label: 'errorcs', insert: 'throw new SyntaxError(${1:"message"})', detail: 'SyntaxError' },
  { label: 'customerr', insert: 'class ${1:Name}Error extends Error {\n\tconstructor(${2:message}) {\n\t\tsuper(${2:message})\n\t\tthis.name = '${1:Name}Error'\n\t}\n}', detail: 'custom error class' },

  { label: 'noop', insert: '() => {}', detail: 'no-op' },
  { label: 'identity', insert: '(x) => x', detail: 'identity function' },
  { label: 'pipe', insert: '(${1:fns}) => (${2:x}) => ${3:fns}.reduce((${4:v}, ${5:fn}) => ${5:fn}(${4:v}), ${2:x})', detail: 'pipe' },
  { label: 'compose', insert: '(${1:fns}) => (${2:x}) => ${3:fns}.reduceRight((${4:v}, ${5:fn}) => ${5:fn}(${4:v}), ${2:x})', detail: 'compose' },

  { label: 'debounce', insert: 'function debounce(${1:fn}, ${2:300}) {\n\tlet ${3:id}\n\treturn (...${4:args}) => {\n\t\tclearTimeout(${3:id})\n\t\t${3:id} = setTimeout(() => ${1:fn}(...${4:args}), ${2:300})\n\t}\n}', detail: 'debounce' },
  { label: 'throttle', insert: 'function throttle(${1:fn}, ${2:1000}) {\n\tlet ${3:last} = 0\n\treturn (...${4:args}) => {\n\t\tconst ${5:now} = Date.now()\n\t\tif (${5:now} - ${3:last} >= ${2:1000}) {\n\t\t\t${3:last} = ${5:now}\n\t\t\t${1:fn}(...${4:args})\n\t\t}\n\t}\n}', detail: 'throttle' },
  { label: 'memoize', insert: 'function memoize(${1:fn}) {\n\tconst ${2:cache} = new Map()\n\treturn (...${3:args}) => {\n\t\tconst ${4:key} = JSON.stringify(${3:args})\n\t\tif (${2:cache}.has(${4:key})) return ${2:cache}.get(${4:key})\n\t\tconst ${5:result} = ${1:fn}(...${3:args})\n\t\t${2:cache}.set(${4:key}, ${5:result})\n\t\treturn ${5:result}\n\t}\n}', detail: 'memoize' },

  { label: 'nodefs', insert: "const fs = require('fs')", detail: 'require fs' },
  { label: 'nodepath', insert: "const path = require('path')", detail: 'require path' },
  { label: 'nodehttp', insert: "const http = require('http')", detail: 'require http' },
  { label: 'nodehttps', insert: "const https = require('https')", detail: 'require https' },
  { label: 'nodeos', insert: "const os = require('os')", detail: 'require os' },
  { label: 'nodecp', insert: "const cp = require('child_process')", detail: 'require child_process' },
  { label: 'nodestream', insert: "const { Readable, Writable, Transform } = require('stream')", detail: 'require stream' },
  { label: 'nodeevents', insert: "const { EventEmitter } = require('events')", detail: 'require events' },
  { label: 'nodeutil', insert: "const util = require('util')", detail: 'require util' },
  { label: 'nodenet', insert: "const net = require('net')", detail: 'require net' },
  { label: 'nodeurl', insert: "const url = require('url')", detail: 'require url' },
  { label: 'nodecrypto', insert: "const crypto = require('crypto')", detail: 'require crypto' },
  { label: 'nodefsync', insert: "const fs = require('fs/promises')", detail: 'require fs/promises' },

  { label: 'nhttpserver', insert: "const server = http.createServer((req, res) => {\n\tres.writeHead(200, { 'Content-Type': 'text/plain' })\n\tres.end('Hello World')\n})\nserver.listen(${1:3000})", detail: 'HTTP server' },
  { label: 'nexpress', insert: "const express = require('express')\nconst app = express()\n\napp.get('/', (req, res) => {\n\tres.json({ ok: true })\n})\n\napp.listen(${1:3000})", detail: 'Express server' },

  { label: 'de', insert: '${1:expr} !== undefined ? ${1:expr} : ${2:default}', detail: 'undefined check' },
  { label: 'dn', insert: '${1:expr} !== null ? ${1:expr} : ${2:default}', detail: 'null check' },
  { label: 'dnn', insert: '${1:expr} != null ? ${1:expr} : ${2:default}', detail: 'null/undefined check' },

  { label: 'clg1', insert: 'console.log(${1:a})', detail: 'log 1 arg' },
  { label: 'clg2', insert: 'console.log(${1:a}, ${2:b})', detail: 'log 2 args' },
  { label: 'clg3', insert: 'console.log(${1:a}, ${2:b}, ${3:c})', detail: 'log 3 args' },
  { label: 'clgo', insert: 'console.log(${1:obj})', detail: 'log object' },
  { label: 'clga', insert: 'console.log(${1:arr})', detail: 'log array' },
  { label: 'clgt', insert: `console.log('${1:text}')`, detail: 'log string' },
  { label: 'clgm', insert: 'console.log("${1:message}:", ${2:value})', detail: 'log with label' },

  { label: 'dce', insert: "document.createElement('${1:tag}')", detail: 'create element' },
  { label: 'dq', insert: "document.querySelector('${1:sel}')", detail: 'querySelector' },
  { label: 'dqa', insert: "document.querySelectorAll('${1:sel}')", detail: 'querySelectorAll' },
  { label: 'dgbi', insert: "document.getElementById('${1:id}')", detail: 'getElementById' },

  { label: 'mapf', insert: '.map(${1:x} => ${2:x})', detail: '.map() ultra short' },
  { label: 'filterf', insert: '.filter(${1:x} => ${2:x})', detail: '.filter() ultra short' },
  { label: 'sortf', insert: '.sort((a, b) => a - b)', detail: 'sort ascending' },
  { label: 'sortfd', insert: '.sort((a, b) => b - a)', detail: 'sort descending' },

  { label: 'uniq', insert: '[...new Set(${1:arr})]', detail: 'unique array' },
  { label: 'flatten', insert: '${1:arr}.flat(Infinity)', detail: 'flatten deep' },
  { label: 'compact', insert: '${1:arr}.filter(Boolean)', detail: 'remove falsy' },
  { label: 'chunk', insert: 'Array.from({ length: Math.ceil(${1:arr}.length / ${2:n}) }, (_, ${3:i}) => ${1:arr}.slice(${3:i} * ${2:n}, (${3:i} + 1) * ${2:n}))', detail: 'chunk array' },
  { label: 'group', insert: '${1:arr}.reduce((${2:acc}, ${3:item}) => {\n\tconst ${4:key} = ${3:item}.${5:prop}\n\t;(${2:acc}[${4:key}] ||= []).push(${3:item})\n\treturn ${2:acc}\n}, {})', detail: 'group by' },

  { label: 'isEmail', insert: '/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(${1:email})', detail: 'email regex' },
  { label: 'isUrl', insert: '/^https?:\\/\\/.+/.test(${1:url})', detail: 'URL regex' },
  { label: 'isNum', insert: '/^-?\\d+(\\.\\d+)?$/.test(${1:str})', detail: 'number regex' },
  { label: 'isInt', insert: '/^-?\\d+$/.test(${1:str})', detail: 'integer regex' },

  { label: 'retry', insert: 'async function retry(${1:fn}, ${2:3}, ${3:1000}) {\n\tfor (let ${4:i} = 0; ${4:i} < ${2:3}; ${4:i}++) {\n\t\ttry {\n\t\t\treturn await ${1:fn}()\n\t\t} catch (${5:err}) {\n\t\t\tif (${4:i} === ${2:3} - 1) throw ${5:err}\n\t\t\tawait new Promise(${6:r} => setTimeout(${6:r}, ${3:1000} * ${4:i}))\n\t\t}\n\t}\n}', detail: 'retry function' },
  { label: 'delay', insert: 'const delay = (${1:ms}) => new Promise(${2:r} => setTimeout(${2:r}, ${1:ms}))', detail: 'delay utility' },

  { label: 'env', insert: 'process.env.${1:KEY}', detail: 'process.env' },
  { label: 'cwd', insert: 'process.cwd()', detail: 'process.cwd' },
  { label: 'exit', insert: 'process.exit(${1:0})', detail: 'process.exit' },
  { label: 'argv', insert: 'process.argv', detail: 'process.argv' },
  { label: 'nextTick', insert: 'process.nextTick(${1:fn})', detail: 'process.nextTick' },

  { label: 'esm', insert: "import ${1:name} from '${2:module}'", detail: 'ESM import' },
  { label: 'esmn', insert: "import { ${1:name} } from '${2:module}'", detail: 'ESM import named' },
  { label: 'esma', insert: "import * as ${1:alias} from '${2:module}'", detail: 'ESM import all' },
  { label: 'esmd', insert: "export default ${1:value}", detail: 'ESM export default' },
  { label: 'esme', insert: "export { ${1:name} } from '${2:module}'", detail: 'ESM re-export' },

  { label: 'arrmap', insert: '${1:arr}.map(${2:item} => ${3:item})', detail: 'array map' },
  { label: 'arrfilter', insert: '${1:arr}.filter(${2:item} => ${3:condition})', detail: 'array filter' },
  { label: 'arrfind', insert: '${1:arr}.find(${2:item} => ${3:condition})', detail: 'array find' },
  { label: 'arrreduce', insert: '${1:arr}.reduce((${2:acc}, ${3:item}) => ${4:acc + item}, ${5:0})', detail: 'array reduce' },
  { label: 'arrforeach', insert: '${1:arr}.forEach(${2:item} => {\n\t${3:// body}\n})', detail: 'array forEach' },

  { label: 'arrpush', insert: '${1:arr}.push(${2:item})', detail: 'array push' },
  { label: 'arrpop', insert: '${1:arr}.pop()', detail: 'array pop' },
  { label: 'arrshift', insert: '${1:arr}.shift()', detail: 'array shift' },
  { label: 'arrunshift', insert: '${1:arr}.unshift(${2:item})', detail: 'array unshift' },

  { label: 'objfrom', insert: "Object.fromEntries(${1:arr}.map(${2:x} => [${3:key}, ${4:value}]))", detail: 'array to object' },
  { label: 'objtoarr', insert: "Object.entries(${1:obj})", detail: 'object to array' },

  { label: 'isundef', insert: 'typeof ${1:x} === "undefined"', detail: 'is undefined' },
  { label: 'isnull', insert: '${1:x} === null', detail: 'is null' },
  { label: 'isstr', insert: 'typeof ${1:x} === "string"', detail: 'is string' },
  { label: 'isnum', insert: 'typeof ${1:x} === "number"', detail: 'is number' },
  { label: 'isbool', insert: 'typeof ${1:x} === "boolean"', detail: 'is boolean' },
  { label: 'isobj', insert: 'typeof ${1:x} === "object" && ${1:x} !== null', detail: 'is object' },
  { label: 'isfn', insert: 'typeof ${1:x} === "function"', detail: 'is function' },
  { label: 'isarr', insert: 'Array.isArray(${1:x})', detail: 'is array' },
  { label: 'isnan', insert: 'Number.isNaN(${1:x})', detail: 'Number.isNaN' },
  { label: 'isfin', insert: 'Number.isFinite(${1:x})', detail: 'Number.isFinite' },

  { label: 'randint', insert: 'Math.floor(Math.random() * (${1:max} - ${2:min} + 1)) + ${2:min}', detail: 'random integer in range' },
  { label: 'pick', insert: '${1:arr}[Math.floor(Math.random() * ${1:arr}.length)]', detail: 'random element' },
  { label: 'shuffle', insert: '${1:arr}.slice().sort(() => Math.random() - 0.5)', detail: 'shuffle array' },
  { label: 'sample', insert: '${1:arr}.slice(0, ${2:n})', detail: 'first n elements' },

  { label: 'times', insert: 'Array.from({ length: ${1:n} }, (${2:_}, ${3:i}) => ${4:i})', detail: 'range 0 to n' },
  { label: 'range', insert: 'Array.from({ length: ${2:to} - ${1:from} }, (_, ${3:i}) => ${1:from} + ${3:i})', detail: 'range from to' },
]