import type { Snippet } from './types'

export const pySnippets: Snippet[] = [
  { label: 'def', insert: 'def ${1:name}(${2:params}):\n\t${3:pass}', detail: 'function' },
  { label: 'defr', insert: 'def ${1:name}(${2:params}):\n\treturn ${3:value}', detail: 'function return' },
  { label: 'defd', insert: 'def ${1:name}(${2:params} = ${3:default}):\n\t${4:pass}', detail: 'function default arg' },
  { label: 'adef', insert: 'async def ${1:name}(${2:params}):\n\t${3:pass}', detail: 'async function' },
  { label: 'adefr', insert: 'async def ${1:name}(${2:params}):\n\treturn ${3:value}', detail: 'async return' },
  { label: 'method', insert: 'def ${1:name}(self${2:, params}):\n\t${3:pass}', detail: 'method' },
  { label: 'classmethod', insert: '@classmethod\ndef ${1:name}(cls${2:, params}):\n\t${3:pass}', detail: 'classmethod' },
  { label: 'staticmethod', insert: '@staticmethod\ndef ${1:name}(${2:params}):\n\t${3:pass}', detail: 'staticmethod' },
  { label: 'property', insert: '@property\ndef ${1:name}(self):\n\treturn self._${1:name}', detail: 'property getter' },
  { label: 'setter', insert: '@${1:name}.setter\ndef ${1:name}(self, value):\n\tself._${1:name} = value', detail: 'property setter' },
  { label: 'init', insert: 'def __init__(self${2:, params}):\n\t${3:pass}', detail: '__init__' },
  { label: 'initf', insert: 'def __init__(self${2:, params}):\n\t${3:pass}\n\n\ndef __repr__(self):\n\treturn f\'${4:{self.__class__.__name__}({{self}}})\'', detail: '__init__ + __repr__' },
  { label: 'repr', insert: 'def __repr__(self):\n\treturn f\'${1:{self.__class__.__name__}({{self}}})\'', detail: '__repr__' },
  { label: 'str', insert: 'def __str__(self):\n\treturn ${1:str(self)}', detail: '__str__' },
  { label: 'len', insert: 'def __len__(self):\n\treturn ${1:len(self._data)}', detail: '__len__' },
  { label: 'iter', insert: 'def __iter__(self):\n\treturn iter(${1:self._data})', detail: '__iter__' },
  { label: 'eq', insert: 'def __eq__(self, other):\n\tif not isinstance(other, ${1:ClassName}):\n\t\treturn NotImplemented\n\treturn ${2:self.x == other.x}', detail: '__eq__' },
  { label: 'lt', insert: 'def __lt__(self, other):\n\treturn ${1:self.x < other.x}', detail: '__lt__' },
  { label: 'hash', insert: 'def __hash__(self):\n\treturn hash((${1:self.x}, ${2:self.y}))', detail: '__hash__' },
  { label: 'call', insert: 'def __call__(self${2:, params}):\n\t${3:pass}', detail: '__call__' },
  { label: 'getitem', insert: 'def __getitem__(self, key):\n\treturn ${1:self._data}[key]', detail: '__getitem__' },
  { label: 'setitem', insert: 'def __setitem__(self, key, value):\n\t${1:self._data}[key] = value', detail: '__setitem__' },
  { label: 'delitem', insert: 'def __delitem__(self, key):\n\tdel ${1:self._data}[key]', detail: '__delitem__' },
  { label: 'contains', insert: 'def __contains__(self, item):\n\treturn ${1:item in self._data}', detail: '__contains__' },
  { label: 'enter', insert: 'def __enter__(self):\n\treturn ${1:self}', detail: '__enter__' },
  { label: 'exit', insert: 'def __exit__(self, exc_type, exc_val, exc_tb):\n\t${1:pass}', detail: '__exit__' },
  { label: 'aenter', insert: 'async def __aenter__(self):\n\treturn ${1:self}', detail: '__aenter__' },
  { label: 'aexit', insert: 'async def __aexit__(self, exc_type, exc_val, exc_tb):\n\t${1:pass}', detail: '__aexit__' },

  { label: 'cls', insert: 'class ${1:Name}:\n\tdef __init__(self${2:, params}):\n\t\t${3:pass}', detail: 'class' },
  { label: 'clse', insert: 'class ${1:Name}(${2:Base}):\n\tdef __init__(self${3:, params}):\n\t\tsuper().__init__(${4:args})\n\t\t${5:pass}', detail: 'class extends' },
  { label: 'clsi', insert: 'class ${1:Name}(${2:Mixin}, ${3:Base}):\n\tdef __init__(self${4:, params}):\n\t\t${5:pass}', detail: 'class multiple inheritance' },
  { label: 'clsd', insert: '@dataclass\nclass ${1:Name}:\n\t${2:key}: ${3:type}', detail: 'dataclass' },
  { label: 'clsef', insert: '@dataclass\nfrom dataclasses import field', detail: 'dataclass import' },
  { label: 'abcls', insert: 'from abc import ABC, abstractmethod\n\nclass ${1:Name}(ABC):\n\t@abstractmethod\n\tdef ${2:method}(self):\n\t\tpass', detail: 'abstract class' },
  { label: 'enum', insert: 'from enum import Enum\n\nclass ${1:Name}(Enum):\n\t${2:VALUE} = ${3:1}', detail: 'Enum' },
  { label: 'enumst', insert: 'from enum import StrEnum\n\nclass ${1:Name}(StrEnum):\n\t${2:VALUE} = "${3:value}"', detail: 'StrEnum' },

  { label: 'for', insert: 'for ${1:item} in ${2:iterable}:\n\t${3:pass}', detail: 'for loop' },
  { label: 'forr', insert: 'for ${1:item} in range(${2:n}):\n\t${3:pass}', detail: 'for range' },
  { label: 'fori', insert: 'for ${1:i} in range(len(${2:list})):\n\t${3:pass}', detail: 'for index' },
  { label: 'fore', insert: 'for ${1:i}, ${2:item} in enumerate(${3:iterable}):\n\t${4:pass}', detail: 'for enumerate' },
  { label: 'fork', insert: 'for ${1:key}, ${2:value} in ${3:dict}.items():\n\t${4:pass}', detail: 'for dict items' },
  { label: 'forz', insert: 'for ${1:a}, ${2:b} in zip(${3:list1}, ${4:list2}):\n\t${5:pass}', detail: 'for zip' },
  { label: 'fora', insert: 'for ${1:item} in ${2:iterable}:\n\t${3:pass}\nelse:\n\t${4:# completed without break}', detail: 'for...else' },
  { label: 'wh', insert: 'while ${1:condition}:\n\t${2:pass}', detail: 'while' },
  { label: 'wha', insert: 'while ${1:condition}:\n\t${2:pass}\nelse:\n\t${3:# loop completed}', detail: 'while...else' },
  { label: 'whb', insert: 'while True:\n\t${1:pass}\n\tif ${2:condition}:\n\t\tbreak', detail: 'while break' },

  { label: 'if', insert: 'if ${1:condition}:\n\t${2:pass}', detail: 'if' },
  { label: 'ife', insert: 'if ${1:condition}:\n\t${2:pass}\nelse:\n\t${3:pass}', detail: 'if/else' },
  { label: 'ifee', insert: 'if ${1:condition}:\n\t${2:pass}\nelif ${3:condition}:\n\t${4:pass}\nelse:\n\t${5:pass}', detail: 'if/elif/else' },
  { label: 'ifeif', insert: 'if ${1:cond1}:\n\t${2:pass}\nelif ${3:cond2}:\n\t${4:pass}', detail: 'if/elif' },
  { label: 'tern', insert: '${1:value} if ${2:condition} else ${3:default}', detail: 'ternary' },
  { label: 'ternc', insert: '${1:value} if ${2:condition} else ${3:None}', detail: 'conditional value' },

  { label: 'try', insert: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}', detail: 'try/except' },
  { label: 'trye', insert: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}\nelse:\n\t${5:# success}\nfinally:\n\t${6:# cleanup}', detail: 'try/except/else/finally' },
  { label: 'tryf', insert: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}\nfinally:\n\t${5:# cleanup}', detail: 'try/finally' },
  { label: 'trye', insert: 'try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\t${4:pass}\nelse:\n\t${5:# no exception}', detail: 'try/except/else' },
  { label: 'tryr', insert: 'try:\n\treturn ${1:value}\nexcept ${2:Exception} as ${3:e}:\n\treturn ${4:default}', detail: 'try return' },
  { label: 'tryc', insert: 'try:\n\t${1:pass}\nexcept:\n\tprint(${2:"error"})', detail: 'bare except' },

  { label: 'with', insert: 'with ${1:expression} as ${2:var}:\n\t${3:pass}', detail: 'with statement' },
  { label: 'witha', insert: 'with ${1:expression} as ${2:a}, ${3:other} as ${4:b}:\n\t${5:pass}', detail: 'with multiple' },

  { label: 'imp', insert: 'import ${1:module}', detail: 'import' },
  { label: 'impf', insert: 'from ${1:module} import ${2:name}', detail: 'from import' },
  { label: 'ima', insert: 'from ${1:module} import *', detail: 'from import all' },
  { label: 'impas', insert: 'import ${1:module} as ${2:alias}', detail: 'import as' },
  { label: 'impfs', insert: 'from ${1:module} import ${2:name} as ${3:alias}', detail: 'from import as' },
  { label: 'impi', insert: 'from . import ${1:name}', detail: 'relative import' },
  { label: 'impif', insert: 'from .${1:module} import ${2:name}', detail: 'relative from import' },

  { label: 'lam', insert: 'lambda ${1:params}: ${2:expression}', detail: 'lambda' },
  { label: 'lamd', insert: 'lambda ${1:x}: ${2:x}', detail: 'identity lambda' },

  { label: 'list', insert: '[${1:item} for ${2:item} in ${3:iterable}]', detail: 'list comprehension' },
  { label: 'listf', insert: '[${1:item} for ${2:item} in ${3:iterable} if ${4:condition}]', detail: 'list comprehension filtered' },
  { label: 'listm', insert: '[${1:func}(${2:item}) for ${2:item} in ${3:iterable}]', detail: 'list comprehension mapped' },
  { label: 'dict', insert: '{${1:key}: ${2:value} for ${3:item} in ${4:iterable}}', detail: 'dict comprehension' },
  { label: 'dictf', insert: '{${1:key}: ${2:value} for ${3:item} in ${4:iterable} if ${5:condition}}', detail: 'dict comprehension filtered' },
  { label: 'set', insert: '{${1:item} for ${2:item} in ${3:iterable}}', detail: 'set comprehension' },
  { label: 'setf', insert: '{${1:item} for ${2:item} in ${3:iterable} if ${4:condition}}', detail: 'set comprehension filtered' },
  { label: 'gen', insert: '(${1:item} for ${2:item} in ${3:iterable})', detail: 'generator expression' },

  { label: 'print', insert: 'print(${1:value})', detail: 'print' },
  { label: 'printf', insert: 'print(f"${1:text}")', detail: 'print f-string' },
  { label: 'printk', insert: 'print(f"${1:key}: {${2:value}}")', detail: 'print key-value' },
  { label: 'printe', insert: 'print(${1:value}, end="${2:}")', detail: 'print end' },
  { label: 'printr', insert: 'print(${1:value}, flush=True)', detail: 'print flush' },
  { label: 'input', insert: '${1:name} = input("${2:prompt}: ")', detail: 'input' },
  { label: 'inputi', insert: '${1:name} = int(input("${2:prompt}: "))', detail: 'input int' },
  { label: 'inputf', insert: '${1:name} = float(input("${2:prompt}: "))', detail: 'input float' },

  { label: 'main', insert: "if __name__ == '__main__':\n\t${1:main()}", detail: 'main guard' },
  { label: 'ifname', insert: "if __name__ == '__main__':\n\t${1:pass}", detail: '__name__ check' },

  { label: 'list', insert: '[${1:items}]', detail: 'list literal' },
  { label: 'lappend', insert: '${1:list}.append(${2:item})', detail: 'list append' },
  { label: 'lextend', insert: '${1:list}.extend(${2:other})', detail: 'list extend' },
  { label: 'linsert', insert: '${1:list}.insert(${2:index}, ${3:item})', detail: 'list insert' },
  { label: 'lremove', insert: '${1:list}.remove(${2:item})', detail: 'list remove' },
  { label: 'lpop', insert: '${1:list}.pop(${2:index})', detail: 'list pop' },
  { label: 'lclear', insert: '${1:list}.clear()', detail: 'list clear' },
  { label: 'lsort', insert: '${1:list}.sort(${2:key=None}, reverse=${3:False})', detail: 'list sort' },
  { label: 'lsorted', insert: 'sorted(${1:list}, key=${2:None}, reverse=${3:False})', detail: 'sorted' },
  { label: 'lrev', insert: '${1:list}.reverse()', detail: 'list reverse' },
  { label: 'lcopy', insert: '${1:list}.copy()', detail: 'list copy' },
  { label: 'lcount', insert: '${1:list}.count(${2:item})', detail: 'list count' },
  { label: 'lindex', insert: '${1:list}.index(${2:item})', detail: 'list index' },

  { label: 'dictd', insert: '{${1:key}: ${2:value}}', detail: 'dict literal' },
  { label: 'dget', insert: '${1:dict}.get(${2:key}, ${3:default})', detail: 'dict get' },
  { label: 'dgetd', insert: '${1:dict}.get(${2:key}, ${3:None})', detail: 'dict get None' },
  { label: 'dset', insert: '${1:dict}[${2:key}] = ${3:value}', detail: 'dict set' },
  { label: 'dupdate', insert: '${1:dict}.update(${2:other})', detail: 'dict update' },
  { label: 'dpop', insert: '${1:dict}.pop(${2:key}, ${3:default})', detail: 'dict pop' },
  { label: 'dkeys', insert: 'list(${1:dict}.keys())', detail: 'dict keys' },
  { label: 'dvalues', insert: 'list(${1:dict}.values())', detail: 'dict values' },
  { label: 'ditems', insert: 'list(${1:dict}.items())', detail: 'dict items' },
  { label: 'dclear', insert: '${1:dict}.clear()', detail: 'dict clear' },
  { label: 'dcopy', insert: '${1:dict}.copy()', detail: 'dict copy' },
  { label: 'dfrom', insert: 'dict(${1:items})', detail: 'dict from items' },
  { label: 'dsetdefault', insert: '${1:dict}.setdefault(${2:key}, ${3:default})', detail: 'dict setdefault' },
  { label: 'dmerge', insert: '{**${1:dict1}, **${2:dict2}}', detail: 'dict merge' },

  { label: 'sadd', insert: '${1:set}.add(${2:item})', detail: 'set add' },
  { label: 'sremove', insert: '${1:set}.remove(${2:item})', detail: 'set remove' },
  { label: 'sdiscard', insert: '${1:set}.discard(${2:item})', detail: 'set discard' },
  { label: 'spop', insert: '${1:set}.pop()', detail: 'set pop' },
  { label: 'sclear', insert: '${1:set}.clear()', detail: 'set clear' },
  { label: 'sunion', insert: '${1:set1} | ${2:set2}', detail: 'set union' },
  { label: 'sinter', insert: '${1:set1} & ${2:set2}', detail: 'set intersection' },
  { label: 'sdiff', insert: '${1:set1} - ${2:set2}', detail: 'set difference' },
  { label: 'sxor', insert: '${1:set1} ^ ${2:set2}', detail: 'set symmetric difference' },

  { label: 'strf', insert: 'f"${1:text}"', detail: 'f-string' },
  { label: 'strv', insert: f'f"${{1:value}}"' , detail: 'f-string variable' },
  { label: 'strk', insert: 'f"${1:key}: {${2:value}}"', detail: 'f-string key-value' },
  { label: 'strf', insert: 'f"${1:text:.${2:2f}}"', detail: 'f-string format' },
  { label: 'strjoin', insert: '"${1:sep}".join(${2:iterable})', detail: 'str join' },
  { label: 'strsplit', insert: '${1:str}.split(${2:sep})', detail: 'str split' },
  { label: 'strstrip', insert: '${1:str}.strip()', detail: 'str strip' },
  { label: 'strreplace', insert: '${1:str}.replace(${2:old}, ${3:new})', detail: 'str replace' },
  { label: 'strfind', insert: '${1:str}.find(${2:substr})', detail: 'str find' },
  { label: 'strcount', insert: '${1:str}.count(${2:substr})', detail: 'str count' },
  { label: 'strstart', insert: '${1:str}.startswith(${2:prefix})', detail: 'str startswith' },
  { label: 'strend', insert: '${1:str}.endswith(${2:suffix})', detail: 'str endswith' },
  { label: 'strlower', insert: '${1:str}.lower()', detail: 'str lower' },
  { label: 'strupper', insert: '${1:str}.upper()', detail: 'str upper' },
  { label: 'strtitle', insert: '${1:str}.title()', detail: 'str title' },
  { label: 'strcenter', insert: '${1:str}.center(${2:width})', detail: 'str center' },
  { label: 'strljust', insert: '${1:str}.ljust(${2:width})', detail: 'str ljust' },
  { label: 'strrjust', insert: '${1:str}.rjust(${2:width})', detail: 'str rjust' },
  { label: 'strzfill', insert: '${1:str}.zfill(${2:width})', detail: 'str zfill' },
  { label: 'strsplitlines', insert: '${1:str}.splitlines()', detail: 'str splitlines' },
  { label: 'strcapitalize', insert: '${1:str}.capitalize()', detail: 'str capitalize' },
  { label: 'strisalnum', insert: '${1:str}.isalnum()', detail: 'str isalnum' },
  { label: 'strisalpha', insert: '${1:str}.isalpha()', detail: 'str isalpha' },
  { label: 'strisdigit', insert: '${1:str}.isdigit()', detail: 'str isdigit' },
  { label: 'strisspace', insert: '${1:str}.isspace()', detail: 'str isspace' },
  { label: 'stristitle', insert: '${1:str}.istitle()', detail: 'str istitle' },
  { label: 'strisupper', insert: '${1:str}.isupper()', detail: 'str isupper' },
  { label: 'strislower', insert: '${1:str}.islower()', detail: 'str islower' },
  { label: 'strisnumeric', insert: '${1:str}.isnumeric()', detail: 'str isnumeric' },

  { label: 'int', insert: 'int(${1:value})', detail: 'int' },
  { label: 'intb', insert: 'int(${1:value}, ${2:base})', detail: 'int base' },
  { label: 'float', insert: 'float(${1:value})', detail: 'float' },
  { label: 'strc', insert: 'str(${1:value})', detail: 'str cast' },
  { label: 'bool', insert: 'bool(${1:value})', detail: 'bool' },
  { label: 'listc', insert: 'list(${1:iterable})', detail: 'list cast' },
  { label: 'tuple', insert: '(${1:items},)', detail: 'tuple' },
  { label: 'tuplec', insert: 'tuple(${1:iterable})', detail: 'tuple cast' },
  { label: 'setc', insert: 'set(${1:iterable})', detail: 'set cast' },
  { label: 'dictc', insert: 'dict(${1:mapping})', detail: 'dict cast' },
  { label: 'type', insert: 'type(${1:value})', detail: 'type' },
  { label: 'isinstance', insert: 'isinstance(${1:value}, ${2:Type})', detail: 'isinstance' },
  { label: 'issubclass', insert: 'issubclass(${1:Class}, ${2:Base})', detail: 'issubclass' },
  { label: 'hasattr', insert: 'hasattr(${1:obj}, "${2:name}")', detail: 'hasattr' },
  { label: 'getattr', insert: 'getattr(${1:obj}, "${2:name}", ${3:default})', detail: 'getattr' },
  { label: 'setattr', insert: 'setattr(${1:obj}, "${2:name}", ${3:value})', detail: 'setattr' },
  { label: 'delattr', insert: 'delattr(${1:obj}, "${2:name}")', detail: 'delattr' },
  { label: 'dir', insert: 'dir(${1:obj})', detail: 'dir' },
  { label: 'vars', insert: 'vars(${1:obj})', detail: 'vars' },
  { label: 'id', insert: 'id(${1:obj})', detail: 'id' },
  { label: 'hash', insert: 'hash(${1:obj})', detail: 'hash' },
  { label: 'repr', insert: 'repr(${1:obj})', detail: 'repr' },
  { label: 'len', insert: 'len(${1:obj})', detail: 'len' },
  { label: 'boolv', insert: 'bool(${1:value})', detail: 'bool value' },

  { label: 'range', insert: 'range(${1:n})', detail: 'range' },
  { label: 'rangea', insert: 'range(${1:start}, ${2:end})', detail: 'range start end' },
  { label: 'ranges', insert: 'range(${1:start}, ${2:end}, ${3:step})', detail: 'range step' },
  { label: 'enumerate', insert: 'enumerate(${1:iterable}, ${2:0})', detail: 'enumerate' },
  { label: 'zip', insert: 'zip(${1:iter1}, ${2:iter2})', detail: 'zip' },
  { label: 'zipc', insert: 'zip(*[${1:list1}, ${2:list2}])', detail: 'zip unzip' },
  { label: 'reversed', insert: 'reversed(${1:iterable})', detail: 'reversed' },
  { label: 'sorted', insert: 'sorted(${1:iterable})', detail: 'sorted' },
  { label: 'sorteda', insert: 'sorted(${1:iterable}, key=${2:None}, reverse=${3:False})', detail: 'sorted args' },
  { label: 'reversed', insert: 'reversed(${1:list})', detail: 'reversed' },

  { label: 'map', insert: 'map(${1:function}, ${2:iterable})', detail: 'map' },
  { label: 'filter', insert: 'filter(${1:function}, ${2:iterable})', detail: 'filter' },
  { label: 'reduce', insert: 'from functools import reduce\nreduce(${1:function}, ${2:iterable})', detail: 'reduce' },
  { label: 'any', insert: 'any(${1:iterable})', detail: 'any' },
  { label: 'all', insert: 'all(${1:iterable})', detail: 'all' },
  { label: 'min', insert: 'min(${1:iterable})', detail: 'min' },
  { label: 'mina', insert: 'min(${1:iterable}, key=${2:None})', detail: 'min with key' },
  { label: 'max', insert: 'max(${1:iterable})', detail: 'max' },
  { label: 'maxa', insert: 'max(${1:iterable}, key=${2:None})', detail: 'max with key' },
  { label: 'sum', insert: 'sum(${1:iterable}, ${2:0})', detail: 'sum' },
  { label: 'sums', insert: 'sum(${1:numbers})', detail: 'sum simple' },
  { label: 'abs', insert: 'abs(${1:value})', detail: 'abs' },
  { label: 'round', insert: 'round(${1:value}, ${2:2})', detail: 'round' },
  { label: 'pow', insert: 'pow(${1:base}, ${2:exp})', detail: 'pow' },
  { label: 'divmod', insert: 'divmod(${1:a}, ${2:b})', detail: 'divmod' },
  { label: 'sorted', insert: 'sorted(${1:iterable})', detail: 'sorted' },

  { label: 'open', insert: "open('${1:file}', '${2:r}')", detail: 'open' },
  { label: 'openr', insert: "with open('${1:file}', 'r') as ${2:f}:\n\t${3:content = f.read()}", detail: 'open read' },
  { label: 'openw', insert: "with open('${1:file}', 'w') as ${2:f}:\n\t${3:f.write(data)}", detail: 'open write' },
  { label: 'opena', insert: "with open('${1:file}', 'a') as ${2:f}:\n\t${3:f.write(data)}", detail: 'open append' },
  { label: 'openb', insert: "with open('${1:file}', 'rb') as ${2:f}:\n\t${3:data = f.read()}", detail: 'open binary' },
  { label: 'readlines', insert: '${1:f}.readlines()', detail: 'readlines' },
  { label: 'writelines', insert: '${1:f}.writelines(${2:lines})', detail: 'writelines' },
  { label: 'readline', insert: '${1:f}.readline()', detail: 'readline' },
  { label: 'tell', insert: '${1:f}.tell()', detail: 'tell' },
  { label: 'seek', insert: '${1:f}.seek(${2:0})', detail: 'seek' },
  { label: 'flush', insert: '${1:f}.flush()', detail: 'flush' },
  { label: 'close', insert: '${1:f}.close()', detail: 'close' },

  { label: 'jsond', insert: "import json\njson.dumps(${1:obj})", detail: 'json dumps' },
  { label: 'jsonl', insert: "import json\njson.loads(${1:str})", detail: 'json loads' },
  { label: 'jsonf', insert: "import json\njson.dump(${1:obj}, ${2:f}, indent=2)", detail: 'json dump file' },
  { label: 'jsonr', insert: "import json\njson.load(${1:f})", detail: 'json load file' },

  { label: 'oslist', insert: 'import os\nos.listdir(${1:path})', detail: 'os.listdir' },
  { label: 'oswalk', insert: 'import os\nfor ${1:root}, ${2:dirs}, ${3:files} in os.walk(${4:path}):\n\t${5:pass}', detail: 'os.walk' },
  { label: 'osjoin', insert: 'os.path.join(${1:path1}, ${2:path2})', detail: 'os.path.join' },
  { label: 'osabs', insert: 'os.path.abspath(${1:path})', detail: 'os.path.abspath' },
  { label: 'osexists', insert: 'os.path.exists(${1:path})', detail: 'os.path.exists' },
  { label: 'osisfile', insert: 'os.path.isfile(${1:path})', detail: 'os.path.isfile' },
  { label: 'osisdir', insert: 'os.path.isdir(${1:path})', detail: 'os.path.isdir' },
  { label: 'osbasename', insert: 'os.path.basename(${1:path})', detail: 'os.path.basename' },
  { label: 'osdirname', insert: 'os.path.dirname(${1:path})', detail: 'os.path.dirname' },
  { label: 'ossize', insert: 'os.path.getsize(${1:path})', detail: 'os.path.getsize' },
  { label: 'osmkdir', insert: 'os.makedirs(${1:path}, exist_ok=True)', detail: 'os.makedirs' },
  { label: 'osremove', insert: 'os.remove(${1:path})', detail: 'os.remove' },
  { label: 'osrename', insert: 'os.rename(${1:old}, ${2:new})', detail: 'os.rename' },
  { label: 'oscopy', insert: 'import shutil\nshutil.copy(${1:src}, ${2:dst})', detail: 'shutil.copy' },
  { label: 'oscopytree', insert: 'import shutil\nshutil.copytree(${1:src}, ${2:dst})', detail: 'shutil.copytree' },
  { label: 'osrmtree', insert: 'import shutil\nshutil.rmtree(${1:path})', detail: 'shutil.rmtree' },
  { label: 'osenv', insert: 'os.environ.get(${1:"KEY"}, ${2:default})', detail: 'os.environ.get' },
  { label: 'osgetcwd', insert: 'os.getcwd()', detail: 'os.getcwd' },
  { label: 'oschdir', insert: 'os.chdir(${1:path})', detail: 'os.chdir' },
  { label: 'oslistdir', insert: 'os.listdir(${1:path})', detail: 'os.listdir' },

  { label: 'datetime', insert: 'from datetime import datetime\ndatetime.now()', detail: 'datetime.now' },
  { label: 'dtnow', insert: 'from datetime import datetime\ndatetime.now()', detail: 'datetime.now' },
  { label: 'dtparse', insert: 'from datetime import datetime\ndatetime.strptime(${1:str}, ${2:"%Y-%m-%d"})', detail: 'datetime.strptime' },
  { label: 'dtformat', insert: '${1:dt}.strftime(${2:"%Y-%m-%d %H:%M:%S"})', detail: 'strftime' },
  { label: 'dtdate', insert: 'from datetime import date\ndate.today()', detail: 'date.today' },
  { label: 'dttime', insert: 'from datetime import time\ntime(${1:hour}, ${2:min}, ${3:sec})', detail: 'time' },
  { label: 'dtdelta', insert: 'from datetime import timedelta\ntimedelta(${1:days}=1)', detail: 'timedelta' },

  { label: 'subprocess', insert: 'import subprocess\nresult = subprocess.run(${1:command}, capture_output=True, text=True)', detail: 'subprocess.run' },
  { label: 'subprocessp', insert: 'import subprocess\nresult = subprocess.Popen(${1:command}, shell=True, stdout=subprocess.PIPE, text=True)', detail: 'subprocess.Popen' },
  { label: 'subprocessc', insert: 'import subprocess\nsubprocess.check_call(${1:command})', detail: 'subprocess.check_call' },
  { label: 'subprocesso', insert: 'import subprocess\noutput = subprocess.check_output(${1:command}, text=True)', detail: 'subprocess.check_output' },

  { label: 'logging', insert: "import logging\nlogging.basicConfig(level=logging.INFO)", detail: 'logging basic' },
  { label: 'logi', insert: "import logging\nlogger = logging.getLogger(__name__)\nlogger.info(${1:'message'})", detail: 'logger info' },
  { label: 'logd', insert: "logger.debug(${1:'message'})", detail: 'logger debug' },
  { label: 'logw', insert: "logger.warning(${1:'message'})", detail: 'logger warning' },
  { label: 'loge', insert: "logger.error(${1:'message'})", detail: 'logger error' },
  { label: 'logc', insert: "logger.critical(${1:'message'})", detail: 'logger critical' },

  { label: 'argparse', insert: "import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument('${1:name}')\nargs = parser.parse_args()", detail: 'argparse' },
  { label: 'argpf', insert: "parser.add_argument('-${1:f}', '--${2:flag}', action='store_true')", detail: 'argparse flag' },
  { label: 'argpo', insert: "parser.add_argument('-${1:o}', '--${2:option}', type=${3:str}, default=${4:None})", detail: 'argparse option' },

  { label: 're.match', insert: "import re\nre.match(r'${1:pattern}', ${2:str})", detail: 're.match' },
  { label: 're.search', insert: "import re\nre.search(r'${1:pattern}', ${2:str})", detail: 're.search' },
  { label: 're.findall', insert: "import re\nre.findall(r'${1:pattern}', ${2:str})", detail: 're.findall' },
  { label: 're.sub', insert: "import re\nre.sub(r'${1:pattern}', ${2:replacement}, ${3:str})", detail: 're.sub' },
  { label: 're.split', insert: "import re\nre.split(r'${1:pattern}', ${2:str})", detail: 're.split' },
  { label: 'recompile', insert: "import re\nre.compile(r'${1:pattern}')", detail: 're.compile' },
  { label: 'regroup', insert: "${1:match}.group(${2:0})", detail: 'match.group' },
  { label: 'regroups', insert: "${1:match}.groups()", detail: 'match.groups' },

  { label: 'thread', insert: "import threading\nt = threading.Thread(target=${1:func}, args=(${2:args}))\nt.start()", detail: 'threading' },
  { label: 'threadpool', insert: "from concurrent.futures import ThreadPoolExecutor\nwith ThreadPoolExecutor(max_workers=${1:4}) as ${2:executor}:\n\t${2:executor}.map(${3:func}, ${4:iterable})", detail: 'ThreadPoolExecutor' },
  { label: 'processpool', insert: "from concurrent.futures import ProcessPoolExecutor\nwith ProcessPoolExecutor(max_workers=${1:4}) as ${2:executor}:\n\t${3:executor}.map(${4:func}, ${5:iterable})", detail: 'ProcessPoolExecutor' },
  { label: 'asyncio', insert: "import asyncio\nasyncio.run(${1:main()})", detail: 'asyncio.run' },
  { label: 'asyncdef', insert: "async def ${1:name}():\n\t${2:pass}", detail: 'async def' },
  { label: 'await', insert: "${1:result} = await ${2:coroutine}", detail: 'await' },
  { label: 'asyncio.create', insert: "asyncio.create_task(${1:coroutine})", detail: 'asyncio.create_task' },
  { label: 'asyncio.gather', insert: "await asyncio.gather(${1:task1}, ${2:task2})", detail: 'asyncio.gather' },
  { label: 'asyncio.wait', insert: "await asyncio.wait([${1:task1}, ${2:task2}])", detail: 'asyncio.wait' },
  { label: 'asyncio.sleep', insert: "await asyncio.sleep(${1:seconds})", detail: 'asyncio.sleep' },

  { label: 'pathlib', insert: "from pathlib import Path\np = Path('${1:path}')", detail: 'pathlib Path' },
  { label: 'pjoin', insert: 'Path(${1:base}) / ${2:"child"}', detail: 'Path join' },
  { label: 'pexists', insert: 'Path(${1:path}).exists()', detail: 'Path.exists' },
  { label: 'pisfile', insert: 'Path(${1:path}).is_file()', detail: 'Path.is_file' },
  { label: 'pisdir', insert: 'Path(${1:path}).is_dir()', detail: 'Path.is_dir' },
  { label: 'pread', insert: 'Path(${1:path}).read_text()', detail: 'Path.read_text' },
  { label: 'pwrite', insert: 'Path(${1:path}).write_text(${2:content})', detail: 'Path.write_text' },
  { label: 'pexists', insert: 'Path(${1:path}).exists()', detail: 'Path.exists' },
  { label: 'pmkdir', insert: 'Path(${1:path}).mkdir(parents=True, exist_ok=True)', detail: 'Path.mkdir' },
  { label: 'prename', insert: 'Path(${1:path}).rename(${2:new_path})', detail: 'Path.rename' },
  { label: 'punlink', insert: 'Path(${1:path}).unlink()', detail: 'Path.unlink' },
  { label: 'pglob', insert: 'Path(${1:path}).glob("${2:*}")', detail: 'Path.glob' },
  { label: 'prglob', insert: 'Path(${1:path}).rglob("${2:*}")', detail: 'Path.rglob' },
  { label: 'piterdir', insert: 'Path(${1:path}).iterdir()', detail: 'Path.iterdir' },
  { label: 'presolve', insert: 'Path(${1:path}).resolve()', detail: 'Path.resolve' },
  { label: 'pabsolute', insert: 'Path(${1:path}).absolute()', detail: 'Path.absolute' },
  { label: 'pparent', insert: 'Path(${1:path}).parent', detail: 'Path.parent' },
  { label: 'pname', insert: 'Path(${1:path}).name', detail: 'Path.name' },
  { label: 'psuffix', insert: 'Path(${1:path}).suffix', detail: 'Path.suffix' },
  { label: 'pstem', insert: 'Path(${1:path}).stem', detail: 'Path.stem' },

  { label: 'dataclass', insert: "from dataclasses import dataclass\n\n@dataclass\nclass ${1:Name}:\n\t${2:key}: ${3:type}", detail: 'dataclass' },
  { label: 'dataclassd', insert: "from dataclasses import dataclass, field\n\n@dataclass\nclass ${1:Name}:\n\t${2:key}: ${3:type} = field(default=${4:value})", detail: 'dataclass default' },
  { label: 'namedtuple', insert: "from collections import namedtuple\n${1:Name} = namedtuple('${1:Name}', [${2:'field1', 'field2'}])", detail: 'namedtuple' },
  { label: 'deque', insert: "from collections import deque\nd = deque(${1:iterable})", detail: 'deque' },
  { label: 'counter', insert: "from collections import Counter\nc = Counter(${1:iterable})", detail: 'Counter' },
  { label: 'defaultdict', insert: "from collections import defaultdict\nd = defaultdict(${1:lambda: ${2:None}})", detail: 'defaultdict' },
  { label: 'ordereddict', insert: "from collections import OrderedDict\nod = OrderedDict()", detail: 'OrderedDict' },

  { label: 'abc', insert: "from abc import ABC, abstractmethod", detail: 'abc import' },
  { label: 'typing', insert: "from typing import ${1:List, Dict, Optional, Tuple}", detail: 'typing import' },
  { label: 'optional', insert: '${1:var}: ${2:str} = None', detail: 'Optional' },
  { label: 'union', insert: '${1:var}: ${2:str} | ${3:int}', detail: 'Union' },
  { label: 'typedlist', insert: '${1:var}: list[${2:str}] = []', detail: 'typed list' },
  { label: 'typeddict', insert: '${1:var}: dict[${2:str}, ${3:any}] = {}', detail: 'typed dict' },
  { label: 'typedtuple', insert: '${1:var}: tuple[${2:str}, ${3:int}] = (${4:"a"}, ${5:1})', detail: 'typed tuple' },

  { label: 'pytest', insert: "def test_${1:name}():\n\tassert ${2:expected} == ${3:actual}", detail: 'pytest test' },
  { label: 'pytesta', insert: "@pytest.mark.parametrize('${1:data}', [${2:(1, 2), (3, 4)}])\ndef test_${3:name}(${1:data}):\n\t${4:pass}", detail: 'pytest parametrize' },
  { label: 'pytestf', insert: "@pytest.fixture\ndef ${1:name}():\n\treturn ${2:value}", detail: 'pytest fixture' },
  { label: 'unittest', insert: "import unittest\n\nclass Test${1:Name}(unittest.TestCase):\n\tdef test_${2:name}(self):\n\t\tself.assertEqual(${3:actual}, ${4:expected})", detail: 'unittest' },

  { label: 'tryg', insert: "try:\n\t${1:pass}\nexcept ${2:Exception}:\n\tpass", detail: 'try/except pass' },
  { label: 'tryw', insert: "try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:e}:\n\tprint(f'Error: {${3:e}}')", detail: 'try except print' },

  { label: 'withf', insert: "with open('${1:file}') as ${2:f}:\n\t${3:data = f.read()}", detail: 'with open file' },
  { label: 'withb', insert: "with open('${1:file}', 'rb') as ${2:f}:\n\t${3:data = f.read()}", detail: 'with open binary' },

  { label: 'printd', insert: 'print(f"${1:key}: {${2:value}}")', detail: 'print dict' },
  { label: 'printr', insert: 'print(repr(${1:value}))', detail: 'print repr' },
  { label: 'printp', insert: 'print(${1:value}, ${2:end=" "})', detail: 'print no newline' },

  { label: 'fstring', insert: "f'${1:text}'", detail: 'f-string single' },
  { label: 'fstringd', insert: 'f"${1:text}"', detail: 'f-string double' },

  { label: 'listdir', insert: 'import os\nos.listdir(${1:path})', detail: 'listdir' },
  { label: 'walk', insert: 'import os\nfor ${1:root}, ${2:dirs}, ${3:files} in os.walk(${4:path}):\n\t${5:pass}', detail: 'os.walk' },
  { label: 'getcwd', insert: 'import os\nos.getcwd()', detail: 'os.getcwd' },
  { label: 'chdir', insert: 'import os\nos.chdir(${1:path})', detail: 'os.chdir' },
  { label: 'mkdir', insert: 'import os\nos.makedirs(${1:path}, exist_ok=True)', detail: 'os.makedirs' },

  { label: 'httpserver', insert: "from http.server import HTTPServer, SimpleHTTPRequestHandler\nserver = HTTPServer(('localhost', ${1:8000}), SimpleHTTPRequestHandler)\nserver.serve_forever()", detail: 'HTTP server' },

  { label: 'flask', insert: "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n\treturn 'Hello World'\n\nif __name__ == '__main__':\n\tapp.run(debug=True)", detail: 'Flask app' },
  { label: 'fastapi', insert: "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/')async def root():\n\treturn {'message': 'Hello World'}", detail: 'FastAPI app' },

  { label: 'pandas', insert: "import pandas as pd\ndf = pd.${1:read_csv}('${2:file.csv}')", detail: 'pandas read' },
  { label: 'numpy', insert: "import numpy as np\narr = np.${1:array}(${2:data})", detail: 'numpy array' },
  { label: 'matplotlib', insert: "import matplotlib.pyplot as plt\nplt.${1:plot}(${2:data})\nplt.show()", detail: 'matplotlib' },

  { label: 'propertyd', insert: '@property\ndef ${1:name}(self):\n\t"""${2:Description}"""\n\treturn self._${1:name}\n\n@${1:name}.setter\ndef ${1:name}(self, value):\n\tself._${1:name} = value', detail: 'property pair' },
  { label: 'classmethodd', insert: '@classmethod\ndef from_${1:factory}(cls, ${2:params}):\n\t${3:pass}', detail: 'classmethod factory' },

  { label: 'context', insert: "from contextlib import contextmanager\n\n@contextmanager\ndef ${1:name}(${2:params}):\n\ttry:\n\t\tyield ${3:value}\n\tfinally:\n\t\t${4:cleanup}", detail: 'contextmanager' },
  { label: 'suppress', insert: "from contextlib import contextmanager\n\nwith suppress(${1:Exception}):\n\t${2:pass}", detail: 'contextlib.suppress' },
  { label: 'exitstack', insert: "from contextlib import ExitStack\n\nwith ExitStack() as ${1:stack}:\n\t${2:pass}", detail: 'ExitStack' },

  { label: 'assert', insert: 'assert ${1:condition}, "${2:message}"', detail: 'assert' },
  { label: 'asserte', insert: 'assert ${1:condition} == ${2:expected}', detail: 'assert equals' },
  { label: 'asserti', insert: 'assert isinstance(${1:value}, ${2:Type})', detail: 'assert isinstance' },

  { label: 'yield', insert: 'yield ${1:value}', detail: 'yield' },
  { label: 'yieldfrom', insert: 'yield from ${1:iterable}', detail: 'yield from' },
  { label: 'genf', insert: "def ${1:name}(${2:params}):\n\tfor ${3:item} in ${4:iterable}:\n\t\tyield ${3:item}", detail: 'generator function' },

  { label: 'slots', insert: "__slots__ = ['${1:attr1}', '${2:attr2}']", detail: '__slots__' },
  { label: 'strformat', insert: '"${1:{}} {}".format(${2:args})', detail: 'str format' },

  { label: 'tryfloat', insert: "try:\n\t${1:value} = float(${2:input})\nexcept ValueError:\n\t${3:pass}", detail: 'try float' },
  { label: 'tryint', insert: "try:\n\t${1:value} = int(${2:input})\nexcept ValueError:\n\t${3:pass}", detail: 'try int' },

  { label: 'withcd', insert: "with open('${1:data}.json', 'r') as ${2:f}:\n\t${3:data = json.load(${2:f})}", detail: 'json load file' },

  { label: 'cli', insert: "import sys\n\ndef main():\n\t${1:pass}\n\nif __name__ == '__main__':\n\tmain()", detail: 'CLI entry' },

  { label: 'env', insert: "import os\nos.environ.get('${1:KEY}', ${2:default})", detail: 'env var' },
  { label: 'environ', insert: "import os\nos.environ['${1:KEY}'] = ${2:'value'}", detail: 'set env' },

  { label: 'hashlib', insert: "import hashlib\nhashlib.${1:sha256}(${2:data}.encode()).hexdigest()", detail: 'hashlib hash' },

  { label: 'base64', insert: "import base64\nbase64.b64encode(${1:data}.encode()).decode()", detail: 'base64 encode' },
  { label: 'b64d', insert: "import base64\nbase64.b64decode(${1:data}).decode()", detail: 'base64 decode' },

  { label: 'uuid', insert: "import uuid\nuuid.uuid4()", detail: 'uuid4' },
  { label: 'uuids', insert: "import uuid\nstr(uuid.uuid4())", detail: 'uuid4 string' },

  { label: 'socket', insert: "import socket\n${1:s} = socket.socket(socket.AF_INET, socket.SOCK_STREAM)", detail: 'socket' },
  { label: 'httpget', insert: "import urllib.request\nresponse = urllib.request.urlopen('${1:url}')", detail: 'urllib GET' },
  { label: 'requests', insert: "import requests\nresponse = requests.get('${1:url}')", detail: 'requests.get' },
  { label: 'requestsp', insert: "import requests\nresponse = requests.post('${1:url}', json=${2:data})", detail: 'requests.post' },
  { label: 'requestss', insert: "import requests\nresponse = requests.get('${1:url}', params=${2:params})", detail: 'requests.get params' },

  { label: 'sqlite', insert: "import sqlite3\nconn = sqlite3.connect('${1:db}.sqlite')\ncursor = conn.cursor()", detail: 'sqlite3 connect' },
  { label: 'sqlquery', insert: "cursor.execute('${1:SELECT * FROM ${2:table}}')", detail: 'sqlite execute' },
  { label: 'sqlfetch', insert: "cursor.fetchall()", detail: 'sqlite fetchall' },
  { label: 'sqlcommit', insert: "conn.commit()", detail: 'sqlite commit' },
  { label: 'sqlclose', insert: "conn.close()", detail: 'sqlite close' },

  { label: 'email', insert: "from email.mime.text import MIMEText\nfrom email.mime.multipart import MIMEMultipart\nmsg = MIMEMultipart()\nmsg['Subject'] = '${1:subject}'\nmsg['From'] = '${2:sender}'\nmsg['To'] = '${3:receiver}'", detail: 'email compose' },

  { label: 'abc', insert: "from abc import ABC, abstractmethod\n\nclass ${1:Name}(ABC):\n\t@abstractmethod\n\tdef ${2:method}(self):\n\t\tpass", detail: 'abstract class' },
  { label: 'protocol', insert: "from typing import Protocol\n\nclass ${1:Name}(Protocol):\n\tdef ${2:method}(self, ${3:params}) -> ${4:return}:\n\t\t...", detail: 'Protocol' },

  { label: 'dataclass', insert: "from dataclasses import dataclass\n\n@dataclass\nclass ${1:Name}:\n\t${2:key}: ${3:type}", detail: 'dataclass' },
  { label: 'dataclassfrozen', insert: "from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass ${1:Name}:\n\t${2:key}: ${3:type}", detail: 'dataclass frozen' },
  { label: 'dataclassorder', insert: "from dataclasses import dataclass\n\n@dataclass(order=True)\nclass ${1:Name}:\n\t${2:key}: ${3:type}", detail: 'dataclass order' },

  { label: 'typeddict', insert: "from typing import TypedDict\n\nclass ${1:Name}(TypedDict):\n\t${2:key}: ${3:type}", detail: 'TypedDict' },
  { label: 'typedlist', insert: "from typing import List\n\n${1:var}: List[${2:str}] = []", detail: 'typed list' },
  { label: 'typeddictt', insert: "from typing import Dict\n\n${1:var}: Dict[${2:str}, ${3:any}] = {}", detail: 'typed dict' },
  { label: 'typedoptional', insert: "from typing import Optional\n\n${1:var}: Optional[${2:str}] = None", detail: 'Optional' },

  { label: 'overload', insert: "from typing import overload\n\n@overload\ndef ${1:name}(${2:a}: ${3:str}) -> ${4:str}: ...\n\n@overload\ndef ${1:name}(${5:a}: ${6:int}) -> ${7:int}: ...\n\ndef ${1:name}(${8:a}: ${9:str | int}):\n\t${10:pass}", detail: 'overload' },

  { label: 'proto', insert: "from typing import Protocol\n\nclass ${1:Name}(Protocol):\n\tdef ${2:method}(self, ${3:params}) -> ${4:return}:\n\t\t...", detail: 'Protocol' },
  { label: 'typevar', insert: "from typing import TypeVar\n${1:T} = TypeVar('${1:T}')", detail: 'TypeVar' },
  { label: 'generics', insert: "from typing import TypeVar, Generic\n${1:T} = TypeVar('${1:T}')\n\nclass ${2:Name}(Generic[${1:T}]):\n\tdef __init__(self, ${3:data}: ${1:T}):\n\t\tself._data = ${3:data}", detail: 'Generic class' },

  { label: 'pydantic', insert: "from pydantic import BaseModel\n\nclass ${1:Name}(BaseModel):\n\t${2:key}: ${3:type}", detail: 'Pydantic model' },

  { label: 'click', insert: "import click\n\n@click.command()\ndef ${1:main}():\n\t${2:pass}", detail: 'Click command' },
  { label: 'clickarg', insert: "@click.argument('${1:name}')", detail: 'Click argument' },
  { label: 'clickopt', insert: "@click.option('-${1:o}', '--${2:option}', default=${3:None})", detail: 'Click option' },

  { label: 'richprint', insert: "from rich import print as rprint\nrprint(${1:value})", detail: 'rich print' },
  { label: 'rtable', insert: "from rich.table import Table\nfrom rich.console import Console\n\nconsole = Console()\ntable = Table()\ntable.add_column('${1:Name}')\nconsole.print(table)", detail: 'rich table' },
]