import type { Snippet } from './types'

export const tsSnippets: Snippet[] = [
  { label: 'clg', insert: 'console.log(${1:data})', detail: 'console.log' },
  { label: 'cw', insert: 'console.warn(${1:data})', detail: 'console.warn' },
  { label: 'ce', insert: 'console.error(${1:data})', detail: 'console.error' },
  { label: 'ci', insert: 'console.info(${1:data})', detail: 'console.info' },
  { label: 'ct', insert: 'console.time(${1:label})\n${2:code}\nconsole.timeEnd(${1:label})', detail: 'console.time' },
  { label: 'cd', insert: 'console.dir(${1:obj}, { depth: null })', detail: 'console.dir' },
  { label: 'ctb', insert: 'console.table(${1:data})', detail: 'console.table' },
  { label: 'cgr', insert: 'console.group(${1:label})', detail: 'console.group' },
  { label: 'cge', insert: 'console.groupEnd()', detail: 'console.groupEnd' },
  { label: 'ccn', insert: 'console.count(${1:label})', detail: 'console.count' },
  { label: 'ccr', insert: 'console.countReset(${1:label})', detail: 'console.countReset' },
  { label: 'ctr', insert: 'console.trace(${1:label})', detail: 'console.trace' },
  { label: 'de', insert: 'debugger', detail: 'debugger' },

  { label: 'fn', insert: 'function ${1:name}(${2:params}): ${3:void} {\n\t${4:// body}\n}', detail: 'function' },
  { label: 'af', insert: 'async function ${1:name}(${2:params}): Promise<${3:void}> {\n\t${4:// body}\n}', detail: 'async function' },
  { label: 'afn', insert: 'async (${1:params}): Promise<${2:void}> => {\n\t${3:// body}\n}', detail: 'async arrow' },
  { label: 'afnc', insert: 'async (${1:params}): Promise<${2:void}> => ${3:value}', detail: 'async arrow concise' },
  { label: 'fni', insert: 'function* ${1:name}(${2:params}): Generator<${3:void}> {\n\t${4:// yield}\n}', detail: 'generator' },
  { label: 'arr', insert: '(${1:params}): ${2:ReturnType} => {\n\t${3:// body}\n}', detail: 'arrow function' },
  { label: 'arrc', insert: '(${1:params}) => ${2:value}', detail: 'arrow concise' },
  { label: 'iife', insert: '(() => {\n\t${1:// body}\n})()', detail: 'IIFE' },
  { label: 'iifea', insert: '(async () => {\n\t${1:// body}\n})()', detail: 'async IIFE' },
  { label: 'mtd', insert: '${1:name}(${2:params}): ${3:void} {\n\t${4:// body}\n}', detail: 'method' },
  { label: 'gmtd', insert: 'get ${1:name}(): ${2:type} {\n\treturn this._${1:name}\n}', detail: 'getter' },
  { label: 'smt', insert: 'set ${1:name}(val: ${2:type}) {\n\tthis._${1:name} = val\n}', detail: 'setter' },
  { label: 'overload', insert: 'function ${1:name}(${2:a}: ${3:string}): ${4:string};\nfunction ${1:name}(${5:a}: ${6:number}): ${7:number};\nfunction ${1:name}(${8:a}: any): any {\n\t${9:// body}\n}', detail: 'function overload' },

  { label: 'int', insert: 'interface ${1:Name} {\n\t${2:key}: ${3:type}\n}', detail: 'interface' },
  { label: 'intx', insert: 'interface ${1:Name} extends ${2:Base} {\n\t${3:key}: ${4:type}\n}', detail: 'interface extends' },
  { label: 'intm', insert: 'interface ${1:Name} extends ${2:Base} {\n\t${3:key}(${4:params}): ${5:ReturnType}\n}', detail: 'interface method' },
  { label: 'ints', insert: 'interface ${1:Name} {\n\t[key: ${2:string}]: ${3:any}\n}', detail: 'interface index signature' },
  { label: 'type', insert: 'type ${1:Name} = ${2:type}', detail: 'type alias' },
  { label: 'union', insert: 'type ${1:Name} = ${2:A} | ${3:B}', detail: 'union type' },
  { label: 'inter', insert: 'type ${1:Name} = ${2:A} & ${3:B}', detail: 'intersection' },
  { label: 'literal', insert: "type ${1:Name} = '${2:a}' | '${3:b}'", detail: 'literal union' },
  { label: 'generic', insert: 'function ${1:name}<${2:T}>(${3:arg}: ${2:T}): ${2:T} {\n\t${4:// body}\n}', detail: 'generic function' },
  { label: 'genericc', insert: 'class ${1:Name}<${2:T}> {\n\t${3:private} ${4:data}: ${2:T}\n\n\tconstructor(${5:data}: ${2:T}) {\n\t\tthis.${5:data} = ${5:data}\n\t}\n}', detail: 'generic class' },
  { label: 'constraint', insert: '<${1:T} extends ${2:string}>', detail: 'generic constraint' },
  { label: 'mapped', insert: 'type ${1:Name}<T> = {\n\t[K in keyof T]: ${2:T[K]}\n}', detail: 'mapped type' },
  { label: 'conditional', insert: 'type ${1:Name}<T> = ${2:T} extends ${3:string} ? ${4:Yes} : ${5:No}', detail: 'conditional type' },
  { label: 'template', insert: 'type ${1:Name} = `${2:a}-${3:b}`', detail: 'template literal type' },
  { label: 'extract', insert: 'type ${1:Name} = ${2:Union} extends ${3:Pattern} ? ${2:Union} : never', detail: 'extract type' },
  { label: 'exclude', insert: 'type ${1:Name} = ${2:Union} extends ${3:Pattern} ? never : ${2:Union}', detail: 'exclude type' },
  { label: 'pick', insert: 'type ${1:Name} = Pick<${2:T}, ${3:keyof ${2:T}}>', detail: 'Pick' },
  { label: 'omit', insert: 'type ${1:Name} = Omit<${2:T}, ${3:keyof ${2:T}}>', detail: 'Omit' },
  { label: 'partial', insert: 'type ${1:Name} = Partial<${2:T}>', detail: 'Partial' },
  { label: 'required', insert: 'type ${1:Name} = Required<${2:T}>', detail: 'Required' },
  { label: 'readonly', insert: 'type ${1:Name} = Readonly<${2:T}>', detail: 'Readonly' },
  { label: 'record', insert: 'type ${1:Name} = Record<${2:string}, ${3:any}>', detail: 'Record' },
  { label: 'promise', insert: 'Promise<${1:void}>', detail: 'Promise type' },
  { label: 'promiseret', insert: 'new Promise<${1:void}>((resolve, reject) => {\n\t${2:// body}\n})', detail: 'new Promise' },
  { label: 'await', insert: 'const ${1:result} = await ${2:promise}', detail: 'await' },
  { label: 'para', insert: 'type ${1:Name} = Parameters<${2:typeof fn}>', detail: 'Parameters' },
  { label: 'rett', insert: 'type ${1:Name} = ReturnType<${2:typeof fn}>', detail: 'ReturnType' },
  { label: 'keysof', insert: 'keyof ${1:T}', detail: 'keyof' },
  { label: 'valof', insert: '${1:T}[keyof ${1:T}]', detail: 'value of' },
  { label: 'typeof', insert: 'typeof ${1:value}', detail: 'typeof' },
  { label: 'nonull', insert: '${1:value}!', detail: 'non-null assertion' },
  { label: 'as', insert: '${1:value} as ${2:Type}', detail: 'type assertion' },
  { label: 'satisfies', insert: '${1:value} satisfies ${2:Type}', detail: 'satisfies' },
  { label: 'infer', insert: 'infer ${1:T}', detail: 'infer' },
  { label: 'asserts', insert: 'asserts ${1:value} is ${2:Type}', detail: 'asserts is' },
  { label: 'never', insert: 'throw new Error(${1:"not implemented"})', detail: 'throw never' },
  { label: 'noop', insert: '() => {}', detail: 'no-op' },
  { label: 'identity', insert: '(x: ${1:T}) => x', detail: 'identity' },

  { label: 'if', insert: 'if (${1:condition}) {\n\t${2:// body}\n}', detail: 'if' },
  { label: 'ife', insert: 'if (${1:condition}) {\n\t${2:// true}\n} else {\n\t${3:// false}\n}', detail: 'if/else' },
  { label: 'ifee', insert: 'if (${1:condition}) {\n\t${2:// body}\n} else if (${3:cond}) {\n\t${4:// body}\n} else {\n\t${5:// default}\n}', detail: 'if/else if/else' },
  { label: 'sw', insert: "switch (${1:value}) {\n\tcase '${2:case}':\n\t\t${3:// body}\n\t\tbreak\n\tdefault:\n\t\t${4:// default}\n}", detail: 'switch' },
  { label: 'tern', insert: '${1:condition} ? ${2:true} : ${3:false}', detail: 'ternary' },
  { label: 'guard', insert: "if (${1:value} instanceof ${2:Type}) {\n\t${3:// narrow}\n}", detail: 'instanceof guard' },
  { label: 'in', insert: "if ('${1:key}' in ${2:obj}) {\n\t${3:// has key}\n}", detail: 'in guard' },
  { label: 'nn', insert: '${1:a} ?? ${2:b}', detail: 'nullish coalescing' },

  { label: 'for', insert: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t${3:// body}\n}', detail: 'for loop' },
  { label: 'forr', insert: 'for (let ${1:i} = ${2:n} - 1; ${1:i} >= 0; ${1:i}--) {\n\t${3:// body}\n}', detail: 'for reverse' },
  { label: 'forof', insert: 'for (const ${1:item} of ${2:iterable}) {\n\t${3:// body}\n}', detail: 'for...of' },
  { label: 'forin', insert: 'for (const ${1:key} in ${2:obj}) {\n\t${3:// body}\n}', detail: 'for...in' },
  { label: 'forofe', insert: 'for (const [${1:key}, ${2:value}] of ${3:Object.entries(obj)}) {\n\t${4:// body}\n}', detail: 'for...of entries' },
  { label: 'wh', insert: 'while (${1:condition}) {\n\t${2:// body}\n}', detail: 'while' },
  { label: 'dwh', insert: 'do {\n\t${1:// body}\n} while (${2:condition})', detail: 'do...while' },

  { label: 'try', insert: 'try {\n\t${1:// code}\n} catch (${2:err}: unknown) {\n\t${3:// handle}\n}', detail: 'try/catch' },
  { label: 'tryf', insert: 'try {\n\t${1:// code}\n} catch (${2:err}: unknown) {\n\t${3:// handle}\n} finally {\n\t${4:// cleanup}\n}', detail: 'try/catch/finally' },
  { label: 'tryret', insert: 'try {\n\t${1:// code}\n\treturn ${2:result}\n} catch (${3:err}: unknown) {\n\treturn ${4:fallback}\n}', detail: 'try with return' },
  { label: 'trya', insert: 'try {\n\t${1:// code}\n} catch (err) {\n\tconsole.error(err)\n}', detail: 'try catch console' },

  { label: 'cls', insert: 'class ${1:Name} {\n\t${2:// fields}\n\n\tconstructor(${3:params}) {\n\t\t${4:// init}\n\t}\n}', detail: 'class' },
  { label: 'clse', insert: 'class ${1:Name} extends ${2:Base} {\n\tconstructor(${3:params}) {\n\t\tsuper(${4:params})\n\t\t${5:// init}\n\t}\n}', detail: 'class extends' },
  { label: 'clsi', insert: 'class ${1:Name} implements ${2:Interface} {\n\t${3:// impl}\n}', detail: 'class implements' },
  { label: 'clseb', insert: 'class ${1:Name} extends ${2:Base} implements ${3:Interface} {\n\tconstructor(${4:params}) {\n\t\tsuper(${5:params})\n\t\t${6:// init}\n\t}\n}', detail: 'class extends implements' },
  { label: 'abs', insert: 'abstract class ${1:Name} {\n\tabstract ${2:method}(${3:params}): ${4:void}\n}', detail: 'abstract class' },
  { label: 'priv', insert: 'private ${1:name}: ${2:type}', detail: 'private field' },
  { label: 'prot', insert: 'protected ${1:name}: ${2:type}', detail: 'protected field' },
  { label: 'stat', insert: 'static ${1:name}: ${2:type}', detail: 'static field' },
  { label: 'readonlyf', insert: 'readonly ${1:name}: ${2:type}', detail: 'readonly field' },
  { label: 'prop', insert: '${1:name} = ${2:value}', detail: 'property initializer' },
  { label: 'privfn', insert: 'private ${1:name}(${2:params}): ${3:void} {\n\t${4:// body}\n}', detail: 'private method' },
  { label: 'statfn', insert: 'static ${1:name}(${2:params}): ${3:void} {\n\t${4:// body}\n}', detail: 'static method' },

  { label: 'imp', insert: "import { ${1:name} } from '${2:path}'", detail: 'import named' },
  { label: 'impd', insert: "import ${1:name} from '${2:path}'", detail: 'import default' },
  { label: 'impa', insert: "import * as ${1:alias} from '${2:path}'", detail: 'import all' },
  { label: 'impt', insert: "import type { ${1:name} } from '${2:path}'", detail: 'import type' },
  { label: 'impi', insert: "import '${1:path}'", detail: 'import side effect' },
  { label: 'exp', insert: 'export { ${1:name} }', detail: 'export named' },
  { label: 'expd', insert: 'export default ${1:value}', detail: 'export default' },
  { label: 'expf', insert: 'export function ${1:name}(${2:params}): ${3:void} {\n\t${4:// body}\n}', detail: 'export function' },
  { label: 'expi', insert: 'export interface ${1:Name} {\n\t${2:key}: ${3:type}\n}', detail: 'export interface' },
  { label: 'expt', insert: 'export type ${1:Name} = ${2:type}', detail: 'export type' },
  { label: 'expa', insert: "export * as ${1:alias} from '${2:path}'", detail: 're-export all as' },
  { label: 'expe', insert: "export { ${1:name} } from '${2:path}'", detail: 're-export' },

  { label: 'map', insert: '.map((${1:item}) => ${2:item})', detail: '.map()' },
  { label: 'mp', insert: '.map(${1:item} => ${2:item})', detail: '.map() short' },
  { label: 'filter', insert: '.filter((${1:item}) => ${2:condition})', detail: '.filter()' },
  { label: 'ft', insert: '.filter(${1:item} => ${2:condition})', detail: '.filter() short' },
  { label: 'reduce', insert: '.reduce((${1:acc}, ${2:item}) => {\n\t${3:return acc}\n}, ${4:init})', detail: '.reduce()' },
  { label: 'find', insert: '.find((${1:item}) => ${2:condition})', detail: '.find()' },
  { label: 'fd', insert: '.find(${1:item} => ${2:condition})', detail: '.find() short' },
  { label: 'findi', insert: '.findIndex((${1:item}) => ${2:condition})', detail: '.findIndex()' },
  { label: 'findl', insert: '.findLast((${1:item}) => ${2:condition})', detail: '.findLast()' },
  { label: 'findli', insert: '.findLastIndex((${1:item}) => ${2:condition})', detail: '.findLastIndex()' },
  { label: 'some', insert: '.some((${1:item}) => ${2:condition})', detail: '.some()' },
  { label: 'every', insert: '.every((${1:item}) => ${2:condition})', detail: '.every()' },
  { label: 'forEach', insert: '.forEach((${1:item}) => {\n\t${2:// body}\n})', detail: '.forEach()' },
  { label: 'fe', insert: '.forEach(${1:item} => {\n\t${2:// body}\n})', detail: '.forEach() short' },
  { label: 'flat', insert: '.flat(${1:1})', detail: '.flat()' },
  { label: 'flatMap', insert: '.flatMap((${1:item}) => ${2:mapped})', detail: '.flatMap()' },
  { label: 'sort', insert: '.sort((${1:a}, ${2:b}) => ${1:a} - ${2:b})', detail: '.sort() numeric' },
  { label: 'sorts', insert: '.sort((${1:a}, ${2:b}) => ${1:a}.localeCompare(${2:b}))', detail: '.sort() string' },
  { label: 'sortd', insert: '.sort((${1:a}, ${2:b}) => ${2:b} - ${1:a})', detail: '.sort() desc' },
  { label: 'reverse', insert: '.reverse()', detail: '.reverse()' },
  { label: 'splice', insert: '.splice(${1:start}, ${2:count})', detail: '.splice()' },
  { label: 'spla', insert: '.splice(${1:start}, ${2:count}, ${3:replacement})', detail: '.splice() replace' },
  { label: 'slice', insert: '.slice(${1:start}, ${2:end})', detail: '.slice()' },
  { label: 'slicen', insert: '.slice(-${1:n})', detail: '.slice() last n' },
  { label: 'concat', insert: '.concat(${1:other})', detail: '.concat()' },
  { label: 'join', insert: '.join(${1:", "})', detail: '.join()' },
  { label: 'split', insert: '.split(${1:delimiter})', detail: '.split()' },
  { label: 'replace', insert: '.replace(${1:search}, ${2:replace})', detail: '.replace()' },
  { label: 'replaceAll', insert: '.replaceAll(${1:search}, ${2:replace})', detail: '.replaceAll()' },
  { label: 'trim', insert: '.trim()', detail: '.trim()' },
  { label: 'trimL', insert: '.trimStart()', detail: '.trimStart()' },
  { label: 'trimR', insert: '.trimEnd()', detail: '.trimEnd()' },
  { label: 'padS', insert: '.padStart(${1:length}, ${2:"0"})', detail: '.padStart()' },
  { label: 'padE', insert: '.padEnd(${1:length}, ${2:" "})', detail: '.padEnd()' },
  { label: 'repeat', insert: '.repeat(${1:count})', detail: '.repeat()' },
  { label: 'match', insert: '.match(${1:/regex/})', detail: '.match()' },
  { label: 'matchAll', insert: '.matchAll(${1:/regex/})', detail: '.matchAll()' },
  { label: 'search', insert: '.search(${1:/regex/})', detail: '.search()' },
  { label: 'startsWith', insert: '.startsWith(${1:value})', detail: '.startsWith()' },
  { label: 'endsWith', insert: '.endsWith(${1:value})', detail: '.endsWith()' },
  { label: 'includes', insert: '.includes(${1:value})', detail: '.includes()' },
  { label: 'indexof', insert: '.indexOf(${1:value})', detail: '.indexOf()' },
  { label: 'lastindexof', insert: '.lastIndexOf(${1:value})', detail: '.lastIndexOf()' },
  { label: 'at', insert: '.at(${1:index})', detail: '.at()' },
  { label: 'charA', insert: '.charAt(${1:index})', detail: '.charAt()' },
  { label: 'charC', insert: '.charCodeAt(${1:index})', detail: '.charCodeAt()' },
  { label: 'locale', insert: '.localeCompare(${1:other})', detail: '.localeCompare()' },
  { label: 'toL', insert: '.toLowerCase()', detail: '.toLowerCase()' },
  { label: 'toU', insert: '.toUpperCase()', detail: '.toUpperCase()' },
  { label: 'substr', insert: '.substring(${1:start}, ${2:end})', detail: '.substring()' },
  { label: 'num', insert: 'Number(${1:value})', detail: 'Number()' },
  { label: 'intp', insert: 'parseInt(${1:value}, ${2:10})', detail: 'parseInt()' },
  { label: 'flt', insert: 'parseFloat(${1:value})', detail: 'parseFloat()' },

  { label: 'keys', insert: 'Object.keys(${1:obj})', detail: 'Object.keys' },
  { label: 'values', insert: 'Object.values(${1:obj})', detail: 'Object.values' },
  { label: 'entries', insert: 'Object.entries(${1:obj})', detail: 'Object.entries' },
  { label: 'fromEntries', insert: 'Object.fromEntries(${1:entries})', detail: 'Object.fromEntries' },
  { label: 'assign', insert: 'Object.assign(${1:target}, ${2:source})', detail: 'Object.assign' },
  { label: 'create', insert: 'Object.create(${1:prototype})', detail: 'Object.create' },
  { label: 'freeze', insert: 'Object.freeze(${1:obj})', detail: 'Object.freeze' },
  { label: 'seal', insert: 'Object.seal(${1:obj})', detail: 'Object.seal' },
  { label: 'defineProp', insert: "Object.defineProperty(${1:obj}, '${2:prop}', {\n\tvalue: ${3:value},\n\twritable: ${4:true},\n\tenumerable: ${5:true},\n\tconfigurable: ${6:true}\n})", detail: 'Object.defineProperty' },
  { label: 'hasOwn', insert: "Object.hasOwn(${1:obj}, '${2:prop}')", detail: 'Object.hasOwn' },
  { label: 'is', insert: 'Object.is(${1:a}, ${2:b})', detail: 'Object.is' },

  { label: 'promise', insert: 'new Promise<${1:void}>(${2:(resolve, reject) => {\n\t${3:// body}\n}})', detail: 'new Promise' },
  { label: 'pall', insert: 'Promise.all([${1:p1}, ${2:p2}])', detail: 'Promise.all' },
  { label: 'pallset', insert: 'Promise.allSettled([${1:p1}, ${2:p2}])', detail: 'Promise.allSettled' },
  { label: 'prace', insert: 'Promise.race([${1:p1}, ${2:p2}])', detail: 'Promise.race' },
  { label: 'pany', insert: 'Promise.any([${1:p1}, ${2:p2}])', detail: 'Promise.any' },
  { label: 'presolve', insert: 'Promise.resolve(${1:value})', detail: 'Promise.resolve' },
  { label: 'preject', insert: 'Promise.reject(${1:reason})', detail: 'Promise.reject' },
  { label: 'aw', insert: 'const ${1:result} = await ${2:promise}', detail: 'await' },
  { label: 'awt', insert: 'await ${1:promise}', detail: 'await (no const)' },

  { label: 'fetch', insert: "fetch('${1:url}')", detail: 'fetch' },
  { label: 'fetchj', insert: "fetch('${1:url}').then(${2:r} => ${2:r}.json())", detail: 'fetch JSON' },
  { label: 'fetcha', insert: "fetch('${1:url}', {\n\tmethod: '${2:POST}',\n\theaders: {\n\t\t'Content-Type': 'application/json'\n\t},\n\tbody: JSON.stringify(${3:data})\n})", detail: 'fetch POST' },

  { label: 'timer', insert: 'setTimeout(() => {\n\t${1:// body}\n}, ${2:1000})', detail: 'setTimeout' },
  { label: 'interv', insert: 'setInterval(() => {\n\t${1:// body}\n}, ${2:1000})', detail: 'setInterval' },
  { label: 'timerC', insert: 'const ${1:id} = setTimeout(${2:fn}, ${3:1000})\nclearTimeout(${1:id})', detail: 'setTimeout + clearTimeout' },
  { label: 'intervC', insert: 'const ${1:id} = setInterval(${2:fn}, ${3:1000})\nclearInterval(${1:id})', detail: 'setInterval + clearInterval' },
  { label: 'rAF', insert: 'requestAnimationFrame(${1:callback})', detail: 'requestAnimationFrame' },
  { label: 'cAF', insert: 'cancelAnimationFrame(${1:id})', detail: 'cancelAnimationFrame' },

  { label: 'date', insert: 'new Date()', detail: 'new Date' },
  { label: 'dateNow', insert: 'Date.now()', detail: 'Date.now' },
  { label: 'dateFrom', insert: "new Date('${1:2024-01-01}')", detail: 'Date from string' },
  { label: 'dateTs', insert: 'new Date(${1:timestamp})', detail: 'Date from timestamp' },
  { label: 'dateISO', insert: '${1:date}.toISOString()', detail: 'toISOString' },
  { label: 'dateLocale', insert: '${1:date}.toLocaleDateString()', detail: 'toLocaleDateString' },
  { label: 'dateParse', insert: "Date.parse('${1:2024-01-01}')", detail: 'Date.parse' },

  { label: 'mathPi', insert: 'Math.PI', detail: 'Math.PI' },
  { label: 'mathE', insert: 'Math.E', detail: 'Math.E' },
  { label: 'mathAbs', insert: 'Math.abs(${1:value})', detail: 'Math.abs' },
  { label: 'mathCeil', insert: 'Math.ceil(${1:value})', detail: 'Math.ceil' },
  { label: 'mathFloor', insert: 'Math.floor(${1:value})', detail: 'Math.floor' },
  { label: 'mathRound', insert: 'Math.round(${1:value})', detail: 'Math.round' },
  { label: 'mathTrunc', insert: 'Math.trunc(${1:value})', detail: 'Math.trunc' },
  { label: 'mathMax', insert: 'Math.max(${1:a}, ${2:b})', detail: 'Math.max' },
  { label: 'mathMin', insert: 'Math.min(${1:a}, ${2:b})', detail: 'Math.min' },
  { label: 'mathRandom', insert: 'Math.random()', detail: 'Math.random' },
  { label: 'mathRand', insert: 'Math.floor(Math.random() * ${1:max})', detail: 'random int' },
  { label: 'mathRandR', insert: 'Math.random() * (${1:max} - ${2:min}) + ${2:min}', detail: 'random range' },
  { label: 'mathPow', insert: 'Math.pow(${1:base}, ${2:exp})', detail: 'Math.pow' },
  { label: 'mathSqrt', insert: 'Math.sqrt(${1:value})', detail: 'Math.sqrt' },
  { label: 'mathLog', insert: 'Math.log(${1:value})', detail: 'Math.log' },
  { label: 'mathLog2', insert: 'Math.log2(${1:value})', detail: 'Math.log2' },
  { label: 'mathLog10', insert: 'Math.log10(${1:value})', detail: 'Math.log10' },
  { label: 'mathExp', insert: 'Math.exp(${1:value})', detail: 'Math.exp' },
  { label: 'mathSin', insert: 'Math.sin(${1:value})', detail: 'Math.sin' },
  { label: 'mathCos', insert: 'Math.cos(${1:value})', detail: 'Math.cos' },
  { label: 'mathTan', insert: 'Math.tan(${1:value})', detail: 'Math.tan' },
  { label: 'mathSign', insert: 'Math.sign(${1:value})', detail: 'Math.sign' },

  { label: 'jsonParse', insert: 'JSON.parse(${1:str})', detail: 'JSON.parse' },
  { label: 'jsonStr', insert: 'JSON.stringify(${1:obj})', detail: 'JSON.stringify' },
  { label: 'jsonStrf', insert: 'JSON.stringify(${1:obj}, null, ${2:2})', detail: 'JSON.stringify formatted' },
  { label: 'jsonCopy', insert: 'JSON.parse(JSON.stringify(${1:obj}))', detail: 'deep copy' },

  { label: 'encode', insert: 'encodeURIComponent(${1:str})', detail: 'encodeURIComponent' },
  { label: 'decode', insert: 'decodeURIComponent(${1:str})', detail: 'decodeURIComponent' },
  { label: 'encodeURI', insert: 'encodeURI(${1:str})', detail: 'encodeURI' },
  { label: 'decodeURI', insert: 'decodeURI(${1:str})', detail: 'decodeURI' },
  { label: 'atob', insert: 'atob(${1:str})', detail: 'atob' },
  { label: 'btoa', insert: 'btoa(${1:str})', detail: 'btoa' },

  { label: 'regExp', insert: 'new RegExp(${1:pattern}, ${2:"g"})', detail: 'new RegExp' },
  { label: 'regL', insert: '/${1:pattern}/g', detail: 'regex literal' },
  { label: 'regTest', insert: '${1:regex}.test(${2:str})', detail: 'RegExp.test' },
  { label: 'regExec', insert: '${1:regex}.exec(${2:str})', detail: 'RegExp.exec' },

  { label: 'mapGet', insert: "new Map<${1:K}, ${2:V}>()", detail: 'new Map' },
  { label: 'mapSet', insert: '${1:map}.set(${2:key}, ${3:value})', detail: 'Map.set' },
  { label: 'mapget', insert: '${1:map}.get(${2:key})', detail: 'Map.get' },
  { label: 'mapHas', insert: '${1:map}.has(${2:key})', detail: 'Map.has' },
  { label: 'mapDel', insert: '${1:map}.delete(${2:key})', detail: 'Map.delete' },
  { label: 'mapKeys', insert: '${1:map}.keys()', detail: 'Map.keys' },
  { label: 'mapVals', insert: '${1:map}.values()', detail: 'Map.values' },
  { label: 'mapEnts', insert: '${1:map}.entries()', detail: 'Map.entries' },
  { label: 'mapSize', insert: '${1:map}.size', detail: 'Map.size' },

  { label: 'setNew', insert: 'new Set<${1:T}>()', detail: 'new Set' },
  { label: 'setFrom', insert: 'new Set(${1:arr})', detail: 'Set from array' },
  { label: 'setAdd', insert: '${1:set}.add(${2:value})', detail: 'Set.add' },
  { label: 'setHas', insert: '${1:set}.has(${2:value})', detail: 'Set.has' },
  { label: 'setDel', insert: '${1:set}.delete(${2:value})', detail: 'Set.delete' },
  { label: 'setSize', insert: '${1:set}.size', detail: 'Set.size' },

  { label: 'arrFrom', insert: 'Array.from(${1:arrayLike})', detail: 'Array.from' },
  { label: 'arrIs', insert: 'Array.isArray(${1:value})', detail: 'Array.isArray' },
  { label: 'arrOf', insert: 'Array.of(${1:items})', detail: 'Array.of' },
  { label: 'arrFill', insert: 'new Array<${1:T}>(${2:length}).fill(${3:value})', detail: 'Array fill' },

  { label: 'const', insert: 'const ${1:name}: ${2:type} = ${3:value}', detail: 'const typed' },
  { label: 'let', insert: 'let ${1:name}: ${2:type} = ${3:value}', detail: 'let typed' },
  { label: 'destr', insert: 'const { ${1:key} }: ${2:Type} = ${3:obj}', detail: 'destructuring object' },
  { label: 'destra', insert: 'const [${1:first}, ${2:rest}] = ${3:arr} as ${4:T[]}', detail: 'destructuring array' },
  { label: 'destrd', insert: 'const { ${1:key}: ${2:alias} } = ${3:obj}', detail: 'destructuring rename' },
  { label: 'destrdf', insert: 'const { ${1:key} = ${2:default} } = ${3:obj}', detail: 'destructuring default' },
  { label: 'spread', insert: '...${1:obj}', detail: 'spread' },
  { label: 'restp', insert: '...${1:args}', detail: 'rest params' },
  { label: 'objsp', insert: '{ ...${1:obj}, ${2:key}: ${3:value} }', detail: 'spread + override' },

  { label: 'mapnew', insert: 'new Map<${1:K}, ${2:V}>()', detail: 'new Map typed' },
  { label: 'mapfrom', insert: 'new Map(Object.entries(${1:obj}) as [${2:string}, ${3:any}][])', detail: 'Map from object' },

  { label: 'weakmap', insert: 'new WeakMap<${1:K}, ${2:V}>()', detail: 'WeakMap' },
  { label: 'weakset', insert: 'new WeakSet<${1:T}>()', detail: 'WeakSet' },
  { label: 'weakref', insert: 'new WeakRef(${1:obj})', detail: 'WeakRef' },
  { label: 'proxy', insert: 'new Proxy<${1:T}>(${2:target}, {\n\tget(${3:target}, ${4:prop}) {\n\t\t${5:// intercept get}\n\t},\n\tset(${3:target}, ${4:prop}, ${5:value}) {\n\t\t${6:// intercept set}\n\t}\n})', detail: 'Proxy' },
  { label: 'reflect', insert: 'Reflect.${1:method}(${2:target})', detail: 'Reflect' },

  { label: 'abort', insert: 'new AbortController()', detail: 'AbortController' },
  { label: 'timeout', insert: 'AbortSignal.timeout(${1:ms})', detail: 'AbortSignal.timeout' },
  { label: 'textEncoder', insert: 'new TextEncoder()', detail: 'TextEncoder' },
  { label: 'textDecoder', insert: 'new TextDecoder()', detail: 'TextDecoder' },
  { label: 'url', insert: "new URL('${1:url}')", detail: 'new URL' },
  { label: 'urlp', insert: 'new URLSearchParams(${1:params})', detail: 'new URLSearchParams' },
  { label: 'urla', insert: 'new URL(${1:path}, ${2:base})', detail: 'URL relative' },
  { label: 'crypto', insert: 'crypto.randomUUID()', detail: 'crypto.randomUUID' },
  { label: 'cryptoSha', insert: "crypto.subtle.digest('${1:SHA-256}', ${2:data})", detail: 'crypto.subtle.digest' },
  { label: 'queueMicro', insert: 'queueMicrotask(${1:fn})', detail: 'queueMicrotask' },
  { label: 'structuredClone', insert: 'structuredClone(${1:obj})', detail: 'structuredClone' },

  { label: 'dom', insert: "document.querySelector('${1:selector}')", detail: 'querySelector' },
  { label: 'doma', insert: "document.querySelectorAll('${1:selector}')", detail: 'querySelectorAll' },
  { label: 'domid', insert: "document.getElementById('${1:id}')", detail: 'getElementById' },
  { label: 'domcre', insert: "document.createElement('${1:tag}')", detail: 'createElement' },
  { label: 'adde', insert: '${1:el}.addEventListener(${2:"click"}, ${3:(e) => {\n\t${4:// handler}\n}})', detail: 'addEventListener' },
  { label: 'removee', insert: '${1:el}.removeEventListener(${2:"click"}, ${3:handler})', detail: 'removeEventListener' },
  { label: 'addd', insert: '${1:parent}.appendChild(${2:child})', detail: 'appendChild' },
  { label: 'addb', insert: '${1:parent}.prepend(${2:child})', detail: 'prepend' },
  { label: 'rem', insert: '${1:el}.remove()', detail: 'remove element' },
  { label: 'clone', insert: '${1:el}.cloneNode(${2:true})', detail: 'cloneNode' },
  { label: 'attr', insert: '${1:el}.setAttribute(${2:"name"}, ${3:"value"})', detail: 'setAttribute' },
  { label: 'geta', insert: '${1:el}.getAttribute(${2:"name"})', detail: 'getAttribute' },
  { label: 'hasa', insert: '${1:el}.hasAttribute(${2:"name"})', detail: 'hasAttribute' },
  { label: 'rema', insert: '${1:el}.removeAttribute(${2:"name"})', detail: 'removeAttribute' },
  { label: 'dataset', insert: '${1:el}.dataset[${2:key}]', detail: 'dataset' },
  { label: 'classadd', insert: '${1:el}.classList.add(${2:"class"})', detail: 'classList.add' },
  { label: 'classrem', insert: '${1:el}.classList.remove(${2:"class"})', detail: 'classList.remove' },
  { label: 'classtog', insert: '${1:el}.classList.toggle(${2:"class"})', detail: 'classList.toggle' },
  { label: 'classhas', insert: '${1:el}.classList.contains(${2:"class"})', detail: 'classList.contains' },
  { label: 'styles', insert: '${1:el}.style.${2:prop} = ${3:value}', detail: 'style' },
  { label: 'getcom', insert: "getComputedStyle(${1:el}).${2:prop}", detail: 'getComputedStyle' },
  { label: 'parent', insert: '${1:el}.parentElement', detail: 'parentElement' },
  { label: 'children', insert: '${1:el}.children', detail: 'children' },
  { label: 'first', insert: '${1:el}.firstElementChild', detail: 'firstElementChild' },
  { label: 'last', insert: '${1:el}.lastElementChild', detail: 'lastElementChild' },
  { label: 'prev', insert: '${1:el}.previousElementSibling', detail: 'previousElementSibling' },
  { label: 'nexts', insert: '${1:el}.nextElementSibling', detail: 'nextElementSibling' },
  { label: 'html', insert: '${1:el}.innerHTML', detail: 'innerHTML' },
  { label: 'textc', insert: '${1:el}.textContent', detail: 'textContent' },
  { label: 'inner', insert: '${1:el}.innerText', detail: 'innerText' },
  { label: 'bcr', insert: '${1:el}.getBoundingClientRect()', detail: 'getBoundingClientRect' },

  { label: 'mutation', insert: "new MutationObserver((${1:mutations}) => {\n\t${2:// observe}\n}).observe(${3:target}, { childList: ${4:true}, subtree: ${5:true} })", detail: 'MutationObserver' },
  { label: 'resize', insert: "new ResizeObserver((${1:entries}) => {\n\t${2:// observe}\n}).observe(${3:el})", detail: 'ResizeObserver' },
  { label: 'intersection', insert: "new IntersectionObserver((${1:entries}) => {\n\t${2:// observe}\n}).observe(${3:el})", detail: 'IntersectionObserver' },
  { label: 'perf', insert: 'performance.now()', detail: 'performance.now' },
  { label: 'perfmark', insert: 'performance.mark(${1:"start"})', detail: 'performance.mark' },
  { label: 'perfmeas', insert: 'performance.measure(${1:"duration"}, ${2:"start"})', detail: 'performance.measure' },

  { label: 'storage', insert: "localStorage.setItem('${1:key}', ${2:value})", detail: 'localStorage.setItem' },
  { label: 'storageg', insert: "localStorage.getItem('${1:key}')", detail: 'localStorage.getItem' },
  { label: 'storager', insert: "localStorage.removeItem('${1:key}')", detail: 'localStorage.removeItem' },
  { label: 'session', insert: "sessionStorage.setItem('${1:key}', ${2:value})", detail: 'sessionStorage.setItem' },
  { label: 'sessiong', insert: "sessionStorage.getItem('${1:key}')", detail: 'sessionStorage.getItem' },

  { label: 'postm', insert: "window.postMessage(${1:data}, '${2:*}')", detail: 'postMessage' },
  { label: 'postl', insert: "window.addEventListener('message', (${1:e}) => {\n\t${2:// handle}\n})", detail: 'on message' },
  { label: 'blob', insert: 'new Blob([${1:data}], { type: "${2:text/plain}" })', detail: 'new Blob' },
  { label: 'file', insert: 'new File([${1:data}], ${2:"filename"}, { type: "${3:text/plain}" })', detail: 'new File' },
  { label: 'fd', insert: 'new FormData()', detail: 'new FormData' },
  { label: 'download', insert: "const ${1:a} = document.createElement('a')\n${1:a}.href = URL.createObjectURL(${2:blob})\n${1:a}.download = '${3:filename}'\n${1:a}.click()", detail: 'download file' },

  { label: 'ws', insert: "new WebSocket('${1:url}')", detail: 'new WebSocket' },
  { label: 'wss', insert: '${1:ws}.send(${2:data})', detail: 'ws.send' },
  { label: 'wson', insert: "${1:ws}.onmessage = (${2:e}) => {\n\t${3:// handle}\n}", detail: 'ws.onmessage' },

  { label: 'worker', insert: "new Worker('${1:script}')", detail: 'new Worker' },
  { label: 'workerp', insert: "new SharedWorker('${1:script}')", detail: 'new SharedWorker' },
  { label: 'service', insert: "navigator.serviceWorker.register('${1:script}')", detail: 'serviceWorker.register' },

  { label: 'asynciter', insert: 'async *${1:name}(${2:params}): AsyncGenerator<${3:void}> {\n\t${4:// yield}\n}', detail: 'async generator' },
  { label: 'forawait', insert: 'for await (const ${1:item} of ${2:iterable}) {\n\t${3:// body}\n}', detail: 'for await...of' },

  { label: 'typedArr', insert: 'new Uint8Array(${1:length})', detail: 'Uint8Array' },
  { label: 'int16', insert: 'new Int16Array(${1:length})', detail: 'Int16Array' },
  { label: 'float32', insert: 'new Float32Array(${1:length})', detail: 'Float32Array' },
  { label: 'buffer', insert: 'new ArrayBuffer(${1:length})', detail: 'ArrayBuffer' },

  { label: 'error', insert: 'throw new Error(${1:"message"})', detail: 'throw Error' },
  { label: 'errorr', insert: 'throw new RangeError(${1:"message"})', detail: 'RangeError' },
  { label: 'errort', insert: 'throw new TypeError(${1:"message"})', detail: 'TypeError' },
  { label: 'errorref', insert: 'throw new ReferenceError(${1:"message"})', detail: 'ReferenceError' },
  { label: 'errorcs', insert: 'throw new SyntaxError(${1:"message"})', detail: 'SyntaxError' },
  { label: 'customerr', insert: 'class ${1:Name}Error extends Error {\n\tconstructor(${2:message}: string) {\n\t\tsuper(${2:message})\n\t\tthis.name = '${1:Name}Error'\n\t}\n}', detail: 'custom error class' },

  { label: 'debounce', insert: 'function debounce<${1:T extends (...args: any[]) => any}>(${1:fn}: ${1:T}, ${2:300}): ${1:T} {\n\tlet ${3:id}: ReturnType<typeof setTimeout>\n\treturn ((...${4:args}: any[]) => {\n\t\tclearTimeout(${3:id})\n\t\t${3:id} = setTimeout(() => ${1:fn}(...${4:args}), ${2:300})\n\t}) as ${1:T}\n}', detail: 'debounce' },
  { label: 'throttle', insert: 'function throttle<${1:T extends (...args: any[]) => any}>(${1:fn}: ${1:T}, ${2:1000}): ${1:T} {\n\tlet ${3:last} = 0\n\treturn ((...${4:args}: any[]) => {\n\t\tconst ${5:now} = Date.now()\n\t\tif (${5:now} - ${3:last} >= ${2:1000}) {\n\t\t\t${3:last} = ${5:now}\n\t\t\t${1:fn}(...${4:args})\n\t\t}\n\t}) as ${1:T}\n}', detail: 'throttle' },
  { label: 'memoize', insert: 'function memoize<${1:T extends (...args: any[]) => any}>(${1:fn}: ${1:T}): ${1:T} {\n\tconst ${2:cache} = new Map<string, ReturnType<${1:T}>>()\n\treturn ((...${3:args}: any[]) => {\n\t\tconst ${4:key} = JSON.stringify(${3:args})\n\t\tif (${2:cache}.has(${4:key})) return ${2:cache}.get(${4:key})!\n\t\tconst ${5:result} = ${1:fn}(...${3:args})\n\t\t${2:cache}.set(${4:key}, ${5:result})\n\t\treturn ${5:result}\n\t}) as ${1:T}\n}', detail: 'memoize' },

  { label: 'pipe', insert: 'const pipe = <${1:T}>(${1:fns}: Array<(arg: ${1:T}) => ${1:T}>) =>\n\t(${1:x}: ${1:T}) => ${1:fns}.reduce((${2:v}, ${3:fn}) => ${3:fn}(${2:v}), ${1:x})', detail: 'pipe' },
  { label: 'compose', insert: 'const compose = <${1:T}>(${1:fns}: Array<(arg: ${1:T}) => ${1:T}>) =>\n\t(${1:x}: ${1:T}) => ${1:fns}.reduceRight((${2:v}, ${3:fn}) => ${3:fn}(${2:v}), ${1:x})', detail: 'compose' },
  { label: 'noop', insert: '(): void => {}', detail: 'no-op' },
  { label: 'identity', insert: '(x: ${1:T}): ${1:T} => x', detail: 'identity' },

  { label: 'retry', insert: 'async function retry<${1:T}>(${2:fn}: () => Promise<${1:T}>, ${3:3}, ${4:1000}): Promise<${1:T}> {\n\tfor (let ${5:i} = 0; ${5:i} < ${3:3}; ${5:i}++) {\n\t\ttry {\n\t\t\treturn await ${2:fn}()\n\t\t} catch (${6:err}: unknown) {\n\t\t\tif (${5:i} === ${3:3} - 1) throw ${6:err}\n\t\t\tawait new Promise(${7:r} => setTimeout(${7:r}, ${4:1000} * ${5:i}))\n\t\t}\n\t}\n\tthrow new Error('unreachable')\n}', detail: 'retry' },
  { label: 'delay', insert: 'const delay = (${1:ms}: number): Promise<void> => new Promise(${2:r} => setTimeout(${2:r}, ${1:ms}))', detail: 'delay' },

  { label: 'env', insert: 'process.env.${1:KEY}', detail: 'process.env' },
  { label: 'cwd', insert: 'process.cwd()', detail: 'process.cwd' },
  { label: 'exit', insert: 'process.exit(${1:0})', detail: 'process.exit' },
  { label: 'argv', insert: 'process.argv', detail: 'process.argv' },
  { label: 'nextTick', insert: 'process.nextTick(${1:fn})', detail: 'process.nextTick' },

  { label: 'rfc', insert: 'export default function ${1:Name}(${2:props}: ${3:Props}) {\n\treturn (\n\t\t<div>\n\t\t\t${4:// content}\n\t\t</div>\n\t)\n}', detail: 'React FC' },
  { label: 'rfcp', insert: 'interface ${1:Name}Props {\n\t${2:// props}\n}\n\nexport default function ${1:Name}({ ${3:props} }: ${1:Name}Props) {\n\treturn (\n\t\t<div>\n\t\t\t${4:// content}\n\t\t</div>\n\t)\n}', detail: 'React FC props' },
  { label: 'rfce', insert: 'import React from "react"\n\ninterface ${1:Name}Props {\n\t${2:// props}\n}\n\nconst ${1:Name}: React.FC<${1:Name}Props> = ({ ${3:props} }) => {\n\treturn (\n\t\t<div>\n\t\t\t${4:// content}\n\t\t</div>\n\t)\n}\n\nexport default ${1:Name}', detail: 'React FC class style' },
  { label: 'forwardRef', insert: 'const ${1:Name} = React.forwardRef<${2:Type}, ${3:Props}>((props, ref) => {\n\treturn <div ref={ref}>${4}</div>\n})', detail: 'forwardRef' },
  { label: 'memo', insert: 'const ${1:Name} = React.memo(function ${1:Name}(${2:props}: ${3:Props}) {\n\treturn (${4:<div />})\n})', detail: 'React.memo' },
  { label: 'lazy', insert: "const ${1:Name} = React.lazy(() => import('${2:./Component}'))", detail: 'React.lazy' },
  { label: 'suspense', insert: '<React.Suspense fallback={${1:<div>Loading...</div>}}>\n\t${2:<Component />}\n</React.Suspense>', detail: 'Suspense' },

  { label: 'useState', insert: 'const [${1:state}, set${1/(.*)/${1:/capitalize}/}] = useState<${2:type}>(${3:initial})', detail: 'useState' },
  { label: 'useStatecb', insert: 'const [${1:state}, set${1/(.*)/${1:/capitalize}/}] = useState<${2:type}>(() => {\n\t${3:// init}\n})', detail: 'useState lazy' },
  { label: 'useEffect', insert: 'useEffect(() => {\n\t${1:// effect}\n\treturn () => {\n\t\t${2:// cleanup}\n\t}\n}, [${3:deps}])', detail: 'useEffect' },
  { label: 'useeffectmount', insert: 'useEffect(() => {\n\t${1:// runs once on mount}\n}, [])', detail: 'useEffect mount only' },
  { label: 'useCallback', insert: 'useCallback((${1:params}): ${2:ReturnType} => {\n\t${3:// body}\n}, [${4:deps}])', detail: 'useCallback' },
  { label: 'useMemo', insert: 'useMemo(() => {\n\treturn ${1:value}\n}, [${2:deps}])', detail: 'useMemo' },
  { label: 'useRef', insert: 'const ${1:ref} = useRef<${2:type}>(${3:initialValue})', detail: 'useRef' },
  { label: 'useReducer', insert: 'const [state, dispatch] = useReducer(${1:reducer}, ${2:initialState})', detail: 'useReducer' },
  { label: 'useContext', insert: 'const ${1:value} = useContext(${2:Context})', detail: 'useContext' },
  { label: 'useImperativeHandle', insert: 'useImperativeHandle(${1:ref}, () => ({\n\t${2:// exposed methods}\n}))', detail: 'useImperativeHandle' },
  { label: 'useLayoutEffect', insert: 'useLayoutEffect(() => {\n\t${1:// effect}\n}, [${2:deps}])', detail: 'useLayoutEffect' },
  { label: 'usedebounce', insert: 'const [debouncedValue, setDebouncedValue] = useState<${1:type}>(${2:value})\n\nuseEffect(() => {\n\tconst timer = setTimeout(() => setDebouncedValue(${2:value}), ${3:300})\n\treturn () => clearTimeout(timer)\n}, [${2:value}])', detail: 'debounce pattern' },
  { label: 'usethrottle', insert: 'const lastRun = useRef(Date.now())\n\nuseEffect(() => {\n\tconst timeout = setTimeout(() => {\n\t\tif (Date.now() - lastRun.current >= ${1:1000}) {\n\t\t\t${2:// handler}\n\t\t\tlastRun.current = Date.now()\n\t\t}\n\t}, ${1:1000} - (Date.now() - lastRun.current))\n\treturn () => clearTimeout(timeout)\n}, [${3:deps}])', detail: 'throttle pattern' },
  { label: 'useClickOutside', insert: "const ${1:ref} = useRef<HTMLDivElement>(null)\n\nuseEffect(() => {\n\tconst ${2:handler} = (${3:e}: MouseEvent) => {\n\t\tif (${1:ref}.current && !${1:ref}.current.contains(${3:e}.target as Node)) {\n\t\t\t${4:// close}\n\t\t}\n\t}\n\tdocument.addEventListener('mousedown', ${2:handler})\n\treturn () => document.removeEventListener('mousedown', ${2:handler})\n}, [])', detail: 'useClickOutside' },
  { label: 'useMediaQuery', insert: "const ${1:matches} = (() => {\n\tconst [${2:m}, set${2/(.*)/${1:/capitalize}/}] = useState(window.matchMedia('${3:query}').matches)\n\tuseEffect(() => {\n\t\tconst ${4:mq} = window.matchMedia('${3:query}')\n\t\tconst ${5:handler} = (${4:e}: MediaQueryListEvent) => set${2/(.*)/${1:/capitalize}/}(${4:e}.matches)\n\t\t${4:mq}.addEventListener('change', ${5:handler})\n\t\treturn () => ${4:mq}.removeEventListener('change', ${5:handler})\n\t}, [])\n\treturn ${2:m}\n})()', detail: 'useMediaQuery' },

  { label: 'ipcHandle', insert: "ipcMain.handle('${1:channel}', async (_, ${2:args}) => {\n\t${3:// handler}\n})", detail: 'ipcMain.handle' },
  { label: 'ipcOn', insert: "ipcMain.on('${1:channel}', (_, ${2:args}) => {\n\t${3:// handler}\n})", detail: 'ipcMain.on' },
  { label: 'ipcInvoke', insert: "ipcRenderer.invoke('${1:channel}', ${2:data})", detail: 'ipcRenderer.invoke' },
  { label: 'ipcSend', insert: "ipcRenderer.send('${1:channel}', ${2:data})", detail: 'ipcRenderer.send' },
  { label: 'bw', insert: 'new BrowserWindow({\n\twidth: ${1:800},\n\theight: ${2:600},\n\twebPreferences: {\n\t\tpreload: ${3:path.join(__dirname, "preload.js")},\n\t\tcontextIsolation: ${4:true},\n\t\tsandbox: ${5:false}\n\t}\n})', detail: 'new BrowserWindow' },
  { label: 'dialog', insert: "dialog.showOpenDialog(${1:win}, {\n\tproperties: ['${2:openFile}']\n})", detail: 'dialog.showOpenDialog' },
  { label: 'readFile', insert: "fs.readFileSync(${1:path}, '${2:utf-8}')", detail: 'fs.readFileSync' },
  { label: 'writeFile', insert: "fs.writeFileSync(${1:path}, ${2:data}, '${3:utf-8}')", detail: 'fs.writeFileSync' },
  { label: 'readDir', insert: "fs.readdirSync(${1:path}, { withFileTypes: ${2:true} })", detail: 'fs.readdirSync' },
  { label: 'mkdir', insert: "fs.mkdirSync(${1:path}, { recursive: ${2:true} })", detail: 'fs.mkdirSync' },
  { label: 'exists', insert: "fs.existsSync(${1:path})", detail: 'fs.existsSync' },
  { label: 'watch', insert: "fs.watch(${1:path}, (${2:event}, ${3:filename}) => {\n\t${4:// handler}\n})", detail: 'fs.watch' },
  { label: 'spawn', insert: "child_process.spawn(${1:command}, ${2:args}, {\n\tcwd: ${3:process.cwd()},\n\tstdio: 'pipe'\n})", detail: 'child_process.spawn' },
  { label: 'exec', insert: "child_process.exec(${1:command}, (err, stdout, stderr) => {\n\t${2:// handle}\n})", detail: 'child_process.exec' },

  { label: 'uniq', insert: '[...new Set(${1:arr})]', detail: 'unique array' },
  { label: 'flatten', insert: '${1:arr}.flat(Infinity)', detail: 'flatten deep' },
  { label: 'compact', insert: '${1:arr}.filter(Boolean)', detail: 'remove falsy' },
  { label: 'chunk', insert: 'Array.from({ length: Math.ceil(${1:arr}.length / ${2:n}) }, (_, ${3:i}) => ${1:arr}.slice(${3:i} * ${2:n}, (${3:i} + 1) * ${2:n}))', detail: 'chunk array' },

  { label: 'group', insert: '${1:arr}.reduce((${2:acc}, ${3:item}) => {\n\tconst ${4:key} = ${3:item}.${5:prop} as string\n\t;(${2:acc}[${4:key}] ||= []).push(${3:item})\n\treturn ${2:acc}\n}, {} as Record<string, typeof ${1:arr}[number][]>)', detail: 'group by' },

  { label: 'mapf', insert: '.map(${1:x} => ${2:x})', detail: '.map() ultra short' },
  { label: 'filterf', insert: '.filter(${1:x} => ${2:x})', detail: '.filter() ultra short' },
  { label: 'sortf', insert: '.sort((a, b) => a - b)', detail: 'sort ascending' },
  { label: 'sortfd', insert: '.sort((a, b) => b - a)', detail: 'sort descending' },

  { label: 'times', insert: 'Array.from({ length: ${1:n} }, (${2:_}, ${3:i}) => ${3:i})', detail: 'range 0 to n' },
  { label: 'range', insert: 'Array.from({ length: ${2:to} - ${1:from} }, (_, ${3:i}) => ${1:from} + ${3:i})', detail: 'range from to' },
]